/* Full local app -> disposable PostgreSQL. No real accounts, GPS or Push. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require('playwright'),{fixture}=require('./team-db-fixture.cjs');
const dir=path.resolve(__dirname,'../..'),source=fs.readFileSync(path.join(dir,'app-v800.js'),'utf8').replace(/\}\)\(\);\s*$/,'window.__timerTest={state,render,reload};})();');
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(name==='config.js')return res.end('window.WORKTIME_CONFIG={supabaseUrl:"https://test.invalid",supabasePublishableKey:"test"}');if(name==='app-v800.js'){res.setHeader('Content-Type','application/javascript');return res.end(source);}if(name==='service-worker.js'){res.statusCode=404;return res.end();}const file=path.resolve(dir,name);if(!file.startsWith(dir+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});
async function main(){const f=await fixture({offers:true,units:true}),{db,ids,actor,admin}=f;let current='business',queue=Promise.resolve(),passed=0,writes=0;const errors=[];
 // Only this disposable PostgreSQL instance gets a deterministic clock.
 // Never run this test clock definition against a production database.
 await db.exec("create or replace function pg_catalog.now() returns timestamptz language sql stable as $$select '2026-10-13T08:00:00Z'::timestamptz$$");
 await db.exec('create role service_role bypassrls');for(const file of ['20261008211721_device_features_v863.sql','20261009100224_appointment_reminders_v865.sql','20261009101042_arrival_timers_v865.sql','20261010095629_admin_device_work_context_v866.sql'])await db.exec(fs.readFileSync(path.join(dir,'supabase/migrations',file),'utf8'));
 const today=(await db.query("select (now() at time zone 'Europe/Berlin')::date::text as work_day")).rows[0].work_day;
 await actor('business');const plan=(await db.query("insert into appointments(employee_id,event_date,customer_id,customer_name,title,notes) values($1,$2,$3,'Klostermanns Hof','Geplante Wartung','ZE-PLAN-1:{\"start\":\"10:00\",\"end\":\"11:00\",\"status\":\"confirmed\"}') returning *",[ids.anna,today,ids.customer])).rows[0];
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});
 try{const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block',geolocation:{latitude:51.5,longitude:7,accuracy:10}});await context.grantPermissions(['geolocation'],{origin:url});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.route('https://test.invalid/**',route=>{queue=queue.then(async()=>{const req=route.request(),u=new URL(req.url()),body=req.postData()?req.postDataJSON():{},method=req.method();const send=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data,(k,v)=>['work_date','event_date','start_date','end_date','receipt_date'].includes(k)&&typeof v==='string'?v.slice(0,10):v)});try{await actor(current);if(u.pathname.includes('/functions/'))return send({});const table=u.pathname.split('/').at(-1);
  if(u.pathname.includes('/rpc/')){const functions={work_order_team_context:['p_company'],set_work_device_context:['p_device','p_employee','p_subscription'],start_job_timer_for_device:['p_device','p_customer','p_appointment','p_source','p_position'],stop_job_timer_for_device:['p_device','p_id'],save_team_work_order_from_device_timer:['p_device','p_timer_id','p_order','p_periods','p_items','p_plan_id'],record_order_arrival_for_device:['p_device','p_order','p_position','p_source'],start_job_timer:['p_customer','p_appointment','p_source','p_position'],stop_job_timer:['p_id'],save_team_work_order_from_timer:['p_timer_id','p_order','p_periods','p_items','p_plan_id'],save_team_work_order:['p_order','p_periods','p_items','p_plan_id']};if(table==='current_business_branding')return send([{id:ids.business,company_name:'Testfirma'}]);if(!functions[table])return send(null);const values=functions[table].map(k=>body[k]&&typeof body[k]==='object'?JSON.stringify(body[k]):body[k]??null);if(table!=='work_order_team_context')writes++;return send((await db.query('select to_jsonb('+table+'('+values.map((_,i)=>'$'+(i+1)).join(',')+')) result',values)).rows[0].result);}
  if(!['profiles','customers','appointments','planning_requests','mailbox_messages','work_days','vacation_requests','time_entries','work_orders','work_order_items','materials','work_order_documents','receipt_scans','company_notification_settings','push_subscriptions','customer_locations','order_arrivals','appointment_reminders','job_timers','work_device_contexts'].includes(table))return send([]);
  const values=[],conditions=[];for(const [k,v]of u.searchParams){if(!/^[a-z_]+$/.test(k))continue;if(v.startsWith('eq.')){values.push(v.slice(3));conditions.push(k+'=$'+values.length);}else if(v==='is.null')conditions.push(k+' is null');}const where=conditions.length?' where '+conditions.join(' and '):'';
  if(method==='GET')return send((await db.query('select * from '+table+where+' limit '+Number(u.searchParams.get('limit')||500)+' offset '+Number(u.searchParams.get('offset')||0),values)).rows);
  writes++;const keys=Object.keys(body),data=Object.values(body).map(v=>v&&typeof v==='object'?JSON.stringify(v):v);
  if(method==='POST')return send((await db.query('insert into '+table+'('+keys.join(',')+') values('+keys.map((_,i)=>'$'+(i+1)).join(',')+') returning *',data)).rows);
  if(method==='PATCH')return send((await db.query('update '+table+' set '+keys.map((k,i)=>k+'=$'+(values.length+i+1)).join(',')+where+' returning *',[...values,...data])).rows);
  throw Error('Unexpected mutation');
 }catch(e){return send({message:e.message,code:e.code},400);}});return queue;});
 await page.clock.setFixedTime(new Date('2026-10-13T08:00:00Z'));
 await page.goto(url);await page.waitForFunction(()=>!!window.__timerTest);
 const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
 const role=async(name,view='home')=>{await queue;await admin();const profile=(await db.query('select * from profiles where id=$1',[ids[name]])).rows[0];current=name;await page.evaluate(async({profile,view,date,business,employee})=>{const a=window.__timerTest;Object.assign(a.state,{profile,session:{user:{id:profile.id},access_token:'synthetic'},businessId:business,employeeId:employee,view,date,month:date.slice(0,7),orderId:'',planId:'',customerId:'',notice:null,planPrefill:null});await a.reload();a.render();},{profile,view,date:today,business:ids.business,employee:ids.anna});};
 await role('business','planning');await page.evaluate(id=>{const a=window.__timerTest;a.state.planId=id;a.render();},plan.id);
 await test('Per-appointment reminder is in planning, not personal settings',async()=>{assert.equal(await page.locator('form[data-form="appointment-reminder"]').count(),1);await page.locator('[name="enabled"]').check();await page.locator('[name="reminder_unit"]').selectOption('hours');await page.locator('[name="reminder_amount"]').fill('2');await page.locator('form[data-form="appointment-reminder"] button.primary').click();await page.waitForFunction(()=>document.querySelector('.reminder-status').textContent.includes('gespeichert'));await admin();assert.equal((await db.query('select reminder_minutes from appointment_reminders')).rows[0].reminder_minutes,120);});
 await test('Reminder save preserves unsaved planning edits and accepts fixed clock',async()=>{await page.locator('form[data-form="planning"] [name="title"]').fill('Nicht verlorener Entwurf');await page.locator('[name="reminder_mode"]').selectOption('clock');await page.locator('[name="notification_time"]').fill('07:00');await page.locator('form[data-form="appointment-reminder"] button.primary').click();await page.waitForFunction(()=>!document.querySelector('form[data-form="appointment-reminder"] button.primary').disabled);assert.equal(await page.locator('form[data-form="planning"] [name="title"]').inputValue(),'Nicht verlorener Entwurf');await admin();assert.equal((await db.query('select notification_time::text value from appointment_reminders')).rows[0].value,'07:00:00');});
 await test('Clock after start is highlighted and does not update saved configuration',async()=>{await page.locator('[name="notification_time"]').fill('12:00');await page.locator('form[data-form="appointment-reminder"] button.primary').click();await page.waitForFunction(()=>!!document.querySelector('[name="notification_time"][aria-invalid="true"]'));await admin();assert.equal((await db.query('select notification_time::text value from appointment_reminders')).rows[0].value,'07:00:00');});
 await role('anna','settings');await test('Settings keep only device permissions and no timing editor',async()=>{assert.equal(await page.locator('form[data-form="notification-settings"],form[data-form="appointment-reminder"]').count(),0);assert.equal(await page.locator('[data-device-action="location-enable"]').count(),1);});
 await role('anna');
 await test('Overview shows timer with no GPS or hour writes before voluntary arrival',async()=>{assert.equal(await page.locator('[data-arrival-timer]').count(),1);await admin();assert.equal((await db.query('select * from job_timers')).rows.length,0);assert.equal((await db.query('select * from time_entries')).rows.length,0);});
 await page.locator('[data-timer-action="start"]').click();await page.waitForSelector('[data-timer-duration]');
 await test('Arrival starts timer with customer; tick preserves unrelated DOM and no time entry',async()=>{assert.match(await page.locator('.timer-running').innerText(),/Klostermanns Hof/);await page.evaluate(()=>document.querySelector('.timer-running').dataset.keep='yes');await page.waitForTimeout(1100);assert.equal(await page.locator('.timer-running').getAttribute('data-keep'),'yes');await admin();assert.equal((await db.query('select * from time_entries')).rows.length,0);});
 await test('Reload keeps active timer and timer click asks driving time before order',async()=>{const id=await page.locator('[data-timer-duration]').getAttribute('data-timer-duration');await page.evaluate(async()=>{const a=window.__timerTest;await a.reload();a.render();});assert.equal(await page.locator('[data-timer-duration]').getAttribute('data-timer-duration'),id);await page.locator('[data-timer-action="finish"]').click();await page.waitForSelector('dialog [name="drive"]');assert.equal(await page.locator('form[data-form="order"]').count(),0);await page.locator('dialog [name="drive"]').fill('0.5');assert.match(await page.locator('.timer-proposal').innerText(),/0,75 h/);});
 await test('Drive time is visible in both editable clocks and hours, plan customer is preserved',async()=>{await page.locator('dialog button.primary').click();await page.waitForSelector('form[data-form="order"][data-timer-id]');assert.equal(await page.locator('[data-team-time="hours"]').inputValue(),'0.75');assert.equal(await page.locator('form[data-form="order"] [name="customer"]').inputValue(),'Klostermanns Hof');const values=await page.locator('[data-team-time="start"],[data-team-time="end"]').evaluateAll(nodes=>nodes.map(n=>n.value));const minutes=t=>Number(t.slice(0,2))*60+Number(t.slice(3));assert.equal(minutes(values[1])-minutes(values[0]),45);await admin();assert.equal((await db.query('select * from time_entries')).rows.length,0);});
 await test('Signed save books only once, closes timer and marks planned work completed',async()=>{await page.evaluate(()=>{const form=document.querySelector('form[data-form="order"]');form.elements.signed_by.value='Testkunde';form.elements.signature_data.value='data:image/png;base64,'+'A'.repeat(220);form.requestSubmit();});await page.waitForFunction(()=>window.__timerTest.state.view==='order-detail'&&window.__timerTest.state.rows.orders.length===1);await admin();const timer=(await db.query('select * from job_timers')).rows[0];assert.ok(timer.consumed_at);assert.equal(timer.work_order_id,plan.id);assert.equal(Number((await db.query('select executed_hours from time_entries')).rows[0].executed_hours),.75);await page.evaluate(()=>{const a=window.__timerTest;a.state.view='home';a.render();});assert.equal(await page.locator('[data-timer-action="finish"]').count(),0);});
 await test('Hour-rounding helper includes before/after travel and retains invalid-day measurements',async()=>{const result=await page.evaluate(()=>{const a=window.WorktimeArrivalTimer;const timer={started_at:'2026-10-09T06:00:00Z',finished_at:'2026-10-09T08:00:00Z'};let error='';try{a.timeProposal({...timer,finished_at:'2026-10-10T08:00:00Z'},0);}catch(e){error=e.message;}return {before:a.timeProposal(timer,30),after:a.timeProposal(timer,30,'after'),error};});assert.equal(result.before.start,'07:30');assert.equal(result.before.end,'10:00');assert.equal(result.after.start,'08:00');assert.equal(result.after.end,'10:30');assert.equal(result.before.hours,2.5);assert.match(result.error,/Kalendertage/);});
 await actor('business');await db.query('insert into customer_locations(customer_id,business_id,latitude,longitude,radius_m) values($1,$2,51.5,7,150)',[ids.customer,ids.business]);await db.query("insert into appointments(employee_id,event_date,customer_id,customer_name,title,notes) values($1,$2,$3,'Klostermanns Hof','GPS Ankunft','ZE-PLAN-1:{\"start\":\"12:00\",\"end\":\"13:00\",\"status\":\"confirmed\"}')",[ids.anna,today,ids.customer]);
 await role('anna','settings');await page.locator('[data-device-action="location-enable"]').click();await page.waitForSelector('[data-device-action="location-disable"]');await page.evaluate(()=>{const a=window.__timerTest;a.state.view='home';a.render();});
 await test('Consented foreground GPS starts timer automatically for assigned customer, no hours booked',async()=>{await page.waitForSelector('[data-timer-duration]');await admin();const timers=(await db.query('select * from job_timers order by started_at')).rows;assert.equal(timers.length,2);assert.equal(timers[1].source,'gps');assert.equal((await db.query('select * from time_entries')).rows.length,1);});
 await test('Timer fits portrait, landscape and desktop',async()=>{for(const size of [{width:320,height:720},{width:390,height:844},{width:844,height:390},{width:1440,height:900}]){await page.setViewportSize(size);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(process.env.DEVICE_QA_OUTPUT_DIR){fs.mkdirSync(process.env.DEVICE_QA_OUTPUT_DIR,{recursive:true});await page.locator('[data-arrival-timer]').screenshot({path:path.join(process.env.DEVICE_QA_OUTPUT_DIR,'timer-'+size.width+'.png')});}}});
 await role('admin','settings');
 await test('Admin starts unbound: changing view employee never silently enables a personal timer',async()=>{assert.equal(await page.locator('form[data-form="work-device-context"]').count(),1);await page.evaluate(()=>{const a=window.__timerTest;a.state.view='home';a.render();});assert.equal(await page.locator('[data-arrival-timer]').count(),0);await page.evaluate(()=>{const a=window.__timerTest;a.state.view='settings';a.render();});});
 await page.locator('[name="work_employee"]').selectOption(ids.anna);await page.locator('form[data-form="work-device-context"] button.primary').click();await page.waitForFunction(()=>document.querySelector('.work-context-status')?.textContent.includes('gespeichert'));
 await test('Admin binds own employee per device and retains real administrator identity',async()=>{assert.equal(await page.evaluate(()=>window.__timerTest.state.profile.role),'administrator');await page.evaluate(()=>{const a=window.__timerTest;a.state.view='home';a.state.employeeId='00000000-0000-4000-8000-000000000005';a.render();});assert.match(await page.locator('[data-arrival-timer]').innerText(),/anna/);assert.match(await page.locator('[data-arrival-timer]').innerText(),/Klostermanns Hof/);assert.equal(await page.locator('[name="timer_customer"] option').filter({hasText:'Anderer Kunde'}).count(),0);});
 await test('Admin timer stays attached to own work account when a different company is viewed',async()=>{await page.evaluate(id=>{const a=window.__timerTest;a.state.businessId=id;a.state.employeeId='00000000-0000-4000-8000-000000000006';a.render();},ids.otherBusiness);assert.equal(await page.locator('[data-timer-duration]').count(),1);assert.match(await page.locator('[data-arrival-timer]').innerText(),/anna/);});
 await test('Opening personal push selects own planning while keeping administrator login',async()=>{await page.evaluate(()=>navigator.serviceWorker.dispatchEvent(new MessageEvent('message',{data:{type:'WORKTIME_OPEN_VIEW',view:'planning'}})));await page.waitForFunction(()=>window.__timerTest.state.view==='planning');assert.equal(await page.evaluate(()=>window.__timerTest.state.businessId),ids.business);assert.equal(await page.evaluate(()=>window.__timerTest.state.employeeId),ids.anna);assert.equal(await page.evaluate(()=>window.__timerTest.state.profile.id),ids.admin);await page.evaluate(()=>{const a=window.__timerTest;a.state.view='home';a.render();});});
 await page.locator('[data-timer-action="finish"]').click();await page.waitForSelector('dialog [name="drive"]');await page.locator('dialog [name="drive"]').fill('0.25');await page.locator('dialog button.primary').click();await page.waitForSelector('form[data-form="order"][data-timer-device]');
 await test('Admin timer opens correct company/worker form without switching authenticated account',async()=>{assert.equal(await page.evaluate(()=>window.__timerTest.state.businessId),ids.business);assert.equal(await page.evaluate(()=>window.__timerTest.state.employeeId),ids.anna);assert.equal(await page.evaluate(()=>window.__timerTest.state.profile.id),ids.admin);assert.equal(await page.locator('[data-team-time="hours"]').inputValue(),'0.5');});
 // Independent synthetic shifts must not overlap the earlier synthetic timer.
 await page.locator('[data-team-time="start"]').fill('05:00');await page.locator('[data-team-time="end"]').fill('05:30');
 await page.evaluate(()=>{const form=document.querySelector('form[data-form="order"]');form.elements.signed_by.value='Testkunde';form.elements.signature_data.value='data:image/png;base64,'+'A'.repeat(220);form.requestSubmit();});await page.waitForFunction(()=>window.__timerTest.state.view==='order-detail'&&window.__timerTest.state.rows.orders.length===2);
 await test('Admin signed timer save books own employee and consumes measurement, without double-counting',async()=>{await admin();const rows=(await db.query('select * from time_entries')).rows;assert.equal(rows.length,2);assert.equal(rows.every(row=>row.employee_id===ids.anna),true);assert.equal((await db.query('select count(*) n from job_timers where consumed_at is null')).rows[0].n,0);});
 await role('admin','settings');
 await test('Admin work-account settings fit mobile portrait, landscape and desktop',async()=>{for(const size of [{width:320,height:720},{width:390,height:844},{width:844,height:390},{width:1440,height:900}]){await page.setViewportSize(size);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(process.env.DEVICE_QA_OUTPUT_DIR)await page.locator('[data-device-settings]').screenshot({path:path.join(process.env.DEVICE_QA_OUTPUT_DIR,'admin-device-'+size.width+'.png')});}});
 await admin();await db.query("insert into appointments(employee_id,event_date,customer_id,customer_name,title,team_employee_ids,notes) values($1,$2,$3,'Klostermanns Hof','Admin GPS',$4,'ZE-PLAN-1:{\"start\":\"14:00\",\"end\":\"15:00\",\"status\":\"confirmed\"}')",[ids.max,today,ids.customer,[ids.anna]]);
 await role('admin','settings');await page.locator('[data-device-action="location-enable"]').click();await page.waitForSelector('[data-device-action="location-disable"]');await page.evaluate(()=>{const a=window.__timerTest;a.state.view='home';a.state.employeeId='00000000-0000-4000-8000-000000000005';a.render();});await context.setGeolocation({latitude:51.500002,longitude:7,accuracy:10});
 await test('Admin foreground GPS starts own bound employee timer even while another employee is selected',async()=>{try{await page.waitForSelector('[data-timer-duration]');}catch(e){console.error(await page.locator('[data-arrival-timer]').innerText());console.error(await page.evaluate(()=>({plans:window.__timerTest.state.rows.appointments,orders:window.__timerTest.state.rows.orders.map(o=>({id:o.id,date:o.work_date})),profile:window.__timerTest.state.profile.id})));throw e;}await admin();const row=(await db.query('select * from job_timers where finished_at is null')).rows[0];assert.equal(row.employee_id,ids.anna);assert.equal(row.source,'gps');assert.equal((await db.query('select count(*) n from time_entries')).rows[0].n,2);assert.equal(await page.evaluate(()=>window.__timerTest.state.profile.id),ids.admin);});
 await test('Admin teammate timer prefills own period without changing plan owner or inventing others hours',async()=>{await page.locator('[data-timer-action="finish"]').click();await page.waitForSelector('dialog [name="drive"]');await page.locator('dialog button.primary').click();await page.waitForSelector('form[data-form="order"][data-timer-device]');assert.equal(await page.evaluate(()=>window.__timerTest.state.employeeId),ids.anna);assert.equal(await page.locator('[data-team-times]').getAttribute('data-team-owner'),ids.max);assert.equal(await page.locator(`[data-team-employee="${ids.anna}"] [data-team-time="hours"]`).inputValue(),'0.25');assert.equal(await page.locator(`[data-team-employee="${ids.max}"] [data-team-time="start"]`).inputValue(),'');assert.equal(await page.evaluate(()=>window.__timerTest.state.profile.id),ids.admin);});
 await role('admin','settings');await test('Personal device binding survives reload and can be explicitly removed',async()=>{assert.equal(await page.locator('[name="work_employee"]').inputValue(),ids.anna);await page.locator('[name="work_employee"]').selectOption('');await page.locator('form[data-form="work-device-context"] button.primary').click();await page.waitForFunction(()=>document.querySelector('.work-context-status')?.textContent.includes('getrennt'));await page.evaluate(()=>{const a=window.__timerTest;a.state.view='home';a.render();});assert.equal(await page.locator('[data-arrival-timer]').count(),0);});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed,runtimeErrors:errors.length,productionWrites:0}));await context.close();
 }finally{await browser.close();await new Promise(r=>server.close(r));await db.close();}
}
main().catch(e=>{console.error(e.stack);process.exit(1);});
