/* Execute the actual shared helpers used by time, work orders and planning. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const source=fs.readFileSync(path.resolve(__dirname,'../../app-v800.js'),'utf8');
const helpers=source.slice(source.indexOf('  function rememberCatalogRow('),source.indexOf('  async function saveMaterials('));
const state={rows:{customers:[],materials:[],people:[]}},writes=[],prompts=[];let choice=null,emptyResponse=false,serial=0,passed=0;
const lower=value=>String(value||'').trim().toLocaleLowerCase('de-DE');
const context=vm.createContext({state,lower,same:(a,b)=>String(a)===String(b),businessId:()=> 'company-a',normalizeUnit:value=>value||'Stk',planningCustomers:employee=>state.rows.customers.filter(c=>c.employee_id===employee||c.company==='company-a'),chooseSimilar:(name,records)=>{prompts.push({name,records});return choice;},write:async(table,data)=>{writes.push({table,data});return emptyResponse?[]:[{...data,id:'created-'+(++serial)}];}});
vm.runInContext(helpers,context);
async function main(){
 const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
 await test('Time/work-order/planning customer helper immediately remembers confirmed new names',async()=>{const row=await context.ensureCustomer('  Krämer  ','worker');assert.equal(row.name,'Krämer');assert.equal(state.rows.customers[0].id,row.id);assert.equal(writes.at(-1).data.employee_id,'worker');const before=writes.length;assert.equal((await context.ensureCustomer('KRÄMER','worker')).id,row.id);assert.equal(writes.length,before);});
 await test('Shared customer helper does not reuse another company customer with the same name',async()=>{state.rows.customers.unshift({id:'foreign',employee_id:'foreign-worker',name:'Firmenkunde'});const row=await context.ensureCustomer('Firmenkunde','worker');assert.notEqual(row.id,'foreign');});
 await test('Declining an existing similar customer creates a separate catalog record',async()=>{state.rows.customers.push({id:'kremer',employee_id:'worker',name:'Kremer'});choice=null;const row=await context.ensureCustomer('Krämer Neu','worker');assert.equal(row.name,'Krämer Neu');assert.ok(state.rows.customers.some(c=>c.id==='kremer'));});
 await test('Accepting a customer suggestion reuses its ID without a catalog write',async()=>{choice=state.rows.customers.find(c=>c.id==='kremer');const before=writes.length;assert.equal((await context.ensureCustomer('Kremer Tippfehler','worker')).id,'kremer');assert.equal(writes.length,before);choice=null;});
 await test('Repeated new work-order articles create exactly one catalog record, even with different case',async()=>{const before=writes.length,first=await context.ensureMaterial(' Hager B16 ','company-a','Kg'),second=await context.ensureMaterial('hager b16','company-a','Stk');assert.equal(first.id,second.id);assert.equal(first.unit,'Kg');assert.equal(first.unit_price,0);assert.equal(writes.length,before+1);assert.equal(state.rows.materials.filter(m=>lower(m.name)==='hager b16').length,1);});
 await test('Materials are shared only within the selected company and retain their existing price/unit',async()=>{state.rows.materials.push({id:'foreign-m',business_id:'company-b',name:'Firmenartikel',unit_price:77,unit:'M'});const row=await context.ensureMaterial('Firmenartikel','company-a','Pau');assert.notEqual(row.id,'foreign-m');const before=writes.length;assert.equal((await context.ensureMaterial('Firmenartikel','company-a','Kg')).unit,'Pau');assert.equal(writes.length,before);assert.equal(state.rows.materials.find(m=>m.id==='foreign-m').unit_price,77);});
 await test('Missing catalog write results stop saving instead of silently dropping a new customer/article',async()=>{emptyResponse=true;await assert.rejects(()=>context.ensureCustomer('Nicht gespeichert','worker'),/Firmenstamm/);await assert.rejects(()=>context.ensureMaterial('Nicht gespeichert','company-a'),/Firmenstamm/);await assert.rejects(()=>context.ensureHourlyMaterial('meister','company-a'),/Firmenstamm/);assert.equal(state.rows.customers.some(c=>c.name==='Nicht gespeichert'),false);assert.equal(state.rows.materials.some(m=>m.name==='Nicht gespeichert'),false);});
 console.log(JSON.stringify({passed,productionWrites:0,sharedEntryHelpers:true}));
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
