/* Local PostgreSQL/RLS tests. Never connects to the production service. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('./team-db-fixture.cjs');
async function main(){
 const f=await fixture({legacyRecords:true,offers:true,units:true,catalog:true}),{db,ids,actor,admin,save,order,periods}=f;let passed=0;
 const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
 const sql=name=>fs.readFileSync(path.resolve(__dirname,'../../supabase/migrations',name),'utf8');
 await db.exec(`create function app_private.protect_hourly_materials() returns trigger language plpgsql as $$begin return old;end;$$; create trigger protect_hourly_materials_on_delete before delete on materials for each row execute function app_private.protect_hourly_materials(); create trigger protect_hourly_materials_on_update before update on materials for each row execute function app_private.protect_hourly_materials();`);
 await db.exec(sql('20261010190525_planning_sync_v867.sql'));
 const snapshot=async()=>JSON.stringify((await db.query("select jsonb_build_object('profiles',(select jsonb_agg(to_jsonb(p) order by id) from profiles p),'orders',(select jsonb_agg(to_jsonb(w) order by id) from work_orders w),'times',(select jsonb_agg(to_jsonb(t) order by id) from time_entries t),'customers',(select jsonb_agg(to_jsonb(c) order by id) from customers c),'materials',(select jsonb_agg(to_jsonb(m) order by id) from materials m),'items',(select jsonb_agg(to_jsonb(i) order by id) from work_order_items i)) data")).rows[0].data);
 const before=await snapshot();await db.exec(sql('20261010194138_customer_labor_rates_v868.sql'));
 const rates=async(customer=ids.customer,value={meister:88.5,monteur:61.25,azubi:29})=>(await db.query('select save_customer_hourly_rates($1,$2) result',[customer,JSON.stringify(value)])).rows[0].result;
 const items=async id=>(await db.query('select position_name,quantity,unit_price,unit from work_order_items where work_order_id=$1 order by position_name',[id])).rows;
 await test('Migration preserves every existing profile, catalog row, order, item and time',async()=>assert.equal(await snapshot(),before));
 await test('Anonymous users cannot read or save customer prices',async()=>{await db.exec('set role anon');await assert.rejects(rates(),/permission denied/);await assert.rejects(db.query('select * from customer_hourly_rates'),/permission denied/);await admin();});
 await actor('business');
 await test('Business saves three customer overrides with exact cents',async()=>{const r=await rates();assert.equal(Number(r.monteur),61.25);assert.equal(Number(r.meister),88.5);assert.equal(Number(r.azubi),29);});
 await test('Direct REST table writes are denied even to business accounts',async()=>{await assert.rejects(db.query('update customer_hourly_rates set monteur=1'),/permission denied/);});
 await test('Other businesses cannot set or read these rates',async()=>{await actor('otherBusiness');await assert.rejects(rates(),/Geschäftsleitung/);assert.equal((await db.query('select * from customer_hourly_rates')).rows.length,0);});
 await test('Employees can read own rates but cannot edit, including private RPC',async()=>{await actor('anna');assert.equal((await db.query('select * from customer_hourly_rates')).rows.length,1);await assert.rejects(rates(),/Geschäftsleitung/);await assert.rejects(db.query('select app_private.save_customer_hourly_rates_v868($1,$2)',[ids.customer,'{"monteur":1}']),/Geschäftsleitung/);});
 await test('A Meister employee is not silently granted management privileges',async()=>{await actor('max');await assert.rejects(rates(),/Geschäftsleitung/);});
 await test('Administrator can configure the selected company customer',async()=>{await actor('admin');assert.equal(Number((await rates()).meister),88.5);});
 await test('Invalid, negative, excessive, fractional-cent and unknown fields are rejected',async()=>{for(const value of [{monteur:-1},{meister:100001},{azubi:4.001},{monteur:'12'},{monteur:true},{monteur:12,company_id:ids.otherBusiness},[]])await assert.rejects(rates(ids.customer,value),/Ungültige|gültigen|Preise/);});
 await test('Missing or foreign customer IDs cannot be used to escape tenancy',async()=>{await actor('business');await assert.rejects(rates(ids.otherCustomer),/Geschäftsleitung/);await assert.rejects(rates('11111111-1111-4111-8111-111111111111'),/Geschäftsleitung/);});
 let saved;
 await test('Employee team save uses server-verified customer rates for every labor class',async()=>{await actor('anna');saved=await save();const rows=await items(saved.id);assert.deepEqual(rows.map(r=>[r.position_name,Number(r.unit_price)]),[['Kabel',2],['Meisterstunde',88.5],['Monteurstunde',61.25]]);assert.equal(rows.find(r=>r.position_name==='Meisterstunde').unit,'H');});
 await test('Changing shared customer contact fields never overwrites management rates',async()=>{await db.query("update customers set custom_fields='{\"email\":\"test@example.invalid\"}' where id=$1",[ids.customer]);assert.equal(Number((await db.query('select monteur from customer_hourly_rates')).rows[0].monteur),61.25);});
 await test('Explicit zero remains zero; null uses the material standard',async()=>{await actor('business');await rates(ids.customer,{monteur:0,meister:null,azubi:null});await actor('anna');saved=await save({...order,id:saved.id});assert.deepEqual((await items(saved.id)).map(r=>[r.position_name,Number(r.unit_price)]),[['Kabel',2],['Meisterstunde',75],['Monteurstunde',0]]);});
 await test('Changes invalidate only the owning firm synchronization stamp',async()=>{await actor('anna');const own=(await db.query('select planning_sync_stamp() s')).rows[0].s;await actor('felix');const other=(await db.query('select planning_sync_stamp() s')).rows[0].s;await actor('business');await rates();await actor('anna');assert.notDeepEqual((await db.query('select planning_sync_stamp() s')).rows[0].s,own);await actor('felix');assert.deepEqual((await db.query('select planning_sync_stamp() s')).rows[0].s,other);});
 await test('Finalizing an open order snapshots current customer prices server-side',async()=>{await actor('business');await rates(ids.customer,{monteur:64,meister:91,azubi:31});await db.query('update work_orders set invoiced=true where id=$1',[saved.id]);assert.deepEqual((await items(saved.id)).map(r=>[r.position_name,Number(r.unit_price)]),[['Kabel',2],['Meisterstunde',91],['Monteurstunde',64]]);});
 await test('Later rate changes never modify a finalized invoice',async()=>{const frozen=await items(saved.id);await rates(ids.customer,{monteur:95,meister:110,azubi:36});assert.deepEqual(await items(saved.id),frozen);await assert.rejects(db.query('update work_order_items set unit_price=1 where work_order_id=$1',[saved.id]),/Abgerechnete/);});
 await test('Azubi is assigned from employee profile and gets its own protected hours item',async()=>{await admin();await db.query("update profiles set labor_type='azubi' where id=$1",[ids.max]);await actor('anna');const azubiOrder=await save({...order,work_date:'2026-10-06'});const azubiItem=(await items(azubiOrder.id)).find(r=>r.position_name==='Auszubildendenstunde');assert.equal(Number(azubiItem.quantity),3);assert.equal(Number(azubiItem.unit_price),36);assert.equal(azubiItem.unit,'H');assert.equal((await db.query("select unit from materials where name='Auszubildendenstunde'")).rows[0].unit,'H');});
 await test('Azubi hourly catalog item cannot be removed, deactivated or renamed',async()=>{await actor('business');assert.equal((await db.query("delete from materials where name='Auszubildendenstunde' returning id")).rows.length,0);await admin();for(const command of ["delete from materials where name='Auszubildendenstunde'","update materials set active=false where name='Auszubildendenstunde'","update materials set name='Something else' where name='Auszubildendenstunde'"])await assert.rejects(db.query(command),/Stundenpositionen/);});
 await test('Empty overrides reset the customer to business defaults',async()=>{await actor('business');await rates(ids.customer,{meister:null,monteur:null,azubi:null});assert.equal((await db.query('select * from customer_hourly_rates')).rows.length,0);});
 await test('All new functions have fixed search paths and anonymous execute is denied',async()=>{await admin();assert.equal((await db.query("select count(*)::int n from pg_proc p join pg_namespace ns on ns.oid=p.pronamespace where ns.nspname in ('public','app_private') and (p.proname like '%v868' or p.proname='save_customer_hourly_rates') and (p.proconfig is null or not exists(select 1 from unnest(p.proconfig) c where c like 'search_path=%'))")).rows[0].n,0);assert.equal((await db.query("select has_function_privilege('anon','public.save_customer_hourly_rates(uuid,jsonb)','execute') allowed")).rows[0].allowed,false);});
 await db.close();console.log(JSON.stringify({passed,production_writes:0}));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
