/* Browser -> disposable PostgreSQL: pricing, permissions, PDF and responsive UI. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require('playwright');
const {fixture}=require('./team-db-fixture.cjs');const directory=path.resolve(__dirname,'../..');
const source=fs.readFileSync(path.join(directory,'app-v800.js'),'utf8').replace(/\}\)\(\);\s*$/,`window.__appTest={state,render,reload,invoiceItemPrice,printInvoicePdf,invoiceGroups};})();`);
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(name==='config.js'){res.setHeader('Content-Type','application/javascript');return res.end('window.WORKTIME_CONFIG={supabaseUrl:"https://test.invalid",supabasePublishableKey:"test"}');}if(name==='app-v800.js'){res.setHeader('Content-Type','application/javascript');return res.end(source);}if(name==='service-worker.js'){res.statusCode=404;return res.end();}const target=path.resolve(directory,name);if(!target.startsWith(directory+path.sep)||!fs.existsSync(target)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',name.endsWith('.css')?'text/css':name.endsWith('.js')?'application/javascript':name.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(target));});
async function main(){const f=await fixture({offers:true,units:true,catalog:true}),{db,ids,actor,admin}=f;let current='business',queue=Promise.resolve(),passed=0;const errors=[];
 await db.exec(fs.readFileSync(path.join(directory,'supabase/migrations/20261010190525_planning_sync_v867.sql'),'utf8'));
 await db.exec(fs.readFileSync(path.join(directory,'supabase/migrations/20261010194138_customer_labor_rates_v868.sql'),'utf8'));
 await actor('anna');const order=await f.save();await admin();
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});
 try{const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());
 await page.route('https://test.invalid/**',route=>{queue=queue.then(async()=>{const req=route.request(),url=new URL(req.url()),body=req.postDataJSON(),method=req.method();const send=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data,(key,value)=>['work_date','event_date','start_date','end_date'].includes(key)&&typeof value==='string'?value.slice(0,10):value)});try{await actor(current);if(url.pathname==='/functions/v1/mailbox-send')return send({recipients:[]});if(url.pathname.includes('/rpc/')){const name=url.pathname.split('/').at(-1);if(name==='save_customer_hourly_rates')return send((await db.query('select save_customer_hourly_rates($1,$2) r',[body.p_customer,JSON.stringify(body.p_rates)])).rows[0].r);if(name==='work_order_team_context')return send((await db.query('select work_order_team_context($1) r',[body.p_company])).rows[0].r);if(name==='planning_sync_stamp')return send((await db.query('select planning_sync_stamp() r')).rows[0].r);return send([]);}const table=url.pathname.split('/').at(-1);if(!['profiles','customers','customer_hourly_rates','materials','work_orders','work_order_items','time_entries','work_days','vacation_requests','appointments','planning_requests','mailbox_messages','work_order_documents'].includes(table))return send([]);if(method==='GET')return send((await db.query('select * from '+table+' order by 1')).rows);throw Error('Unexpected request '+method+' '+table);}catch(e){return send({message:e.message},400);}});return queue;});
 await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>!!window.__appTest);
 const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
 const role=async(name,view='customers')=>{await queue;await admin();const profile=(await db.query('select * from profiles where id=$1',[ids[name]])).rows[0];current=name;await page.evaluate(async({profile,view,company,customer,employee})=>{const a=window.__appTest;Object.assign(a.state,{profile,session:{user:{id:profile.id},access_token:'synthetic'},view,date:'2026-10-05',month:'2026-10',businessId:company,employeeId:profile.role==='employee'?profile.id:employee,customerId:customer,notice:null});await a.reload();a.render();},{profile,view,company:ids.business,customer:ids.customer,employee:ids.anna});};
 await role('business');const form=page.locator('form[data-form="customer-rates"]');
 await test('Business customer detail exposes three independently configurable net hourly rates',async()=>{assert.equal(await form.count(),1);for(const name of ['meister','monteur','azubi'])assert.equal(await form.locator('[name="'+name+'"]').count(),1);assert.match(await form.innerText(),/Meister.*Monteur.*Auszubildender/s);});
 await test('Rate form and employee settings fit portrait, landscape and desktop',async()=>{for(const [width,height] of [[320,740],[390,844],[844,390],[1440,900]]){await page.setViewportSize({width,height});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);}await page.setViewportSize({width:390,height:844});});
 await test('Manager saving really persists and reloads all three fields without changing the customer',async()=>{await form.locator('[name="meister"]').fill('87.50');await form.locator('[name="monteur"]').fill('62.25');await form.locator('[name="azubi"]').fill('28');await form.locator('button').click();await page.waitForFunction(()=>!window.__appTest.state.busy);assert.equal(await form.locator('[name="monteur"]').inputValue(),'62.25');await queue;await admin();assert.equal(Number((await db.query('select monteur from customer_hourly_rates')).rows[0].monteur),62.25);assert.equal((await db.query('select name from customers where id=$1',[ids.customer])).rows[0].name,'Klostermanns Hof');});
 await test('Open labor positions use customer overrides while material prices stay standard',async()=>{const prices=await page.evaluate(id=>{const a=window.__appTest,o=a.state.rows.orders.find(x=>x.id===id);return a.state.rows.items.filter(x=>x.work_order_id===id).map(x=>[x.position_name,a.invoiceItemPrice(x,o)]).sort();},order.id);assert.deepEqual(prices,[['Kabel',2],['Meisterstunde',87.5],['Monteurstunde',62.25]]);});
 await test('Invoice PDF preview includes actual customer-specific hourly prices',async()=>{const popupPromise=page.waitForEvent('popup');await page.evaluate(()=>{const a=window.__appTest;const group=a.invoiceGroups(false)[0];a.printInvoicePdf(group);});const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');const text=await popup.locator('body').innerText();assert.match(text,/62,25/);assert.match(text,/87,50/);assert.match(text,/Meisterstunde/);await popup.close();});
 await test('Explicit zero and cleared overrides round-trip distinctly',async()=>{await form.locator('[name="monteur"]').fill('0');await form.locator('[name="meister"]').fill('');await form.locator('button').click();await page.waitForFunction(()=>!window.__appTest.state.busy);assert.equal(Number(await form.locator('[name="monteur"]').inputValue()),0);assert.equal(await form.locator('[name="meister"]').inputValue(),'');});
 await test('Employees cannot see or edit customer price controls',async()=>{await role('anna');assert.equal(await page.locator('form[data-form="customer-rates"]').count(),0);assert.equal(await page.locator('form[data-form="customer"]').count(),1);});
 await test('Administrator can configure the selected business customer',async()=>{await role('admin');assert.equal(await form.count(),1);});
 await test('Employee classification offers Auszubildender without removing Aushilfe',async()=>{await role('business','settings');assert.equal(await page.locator('form[data-form="employee-labor-type"] option[value="azubi"]').count(),1);assert.equal(await page.locator('form[data-form="employee-labor-type"] option[value="aushilfe"]').count(),1);});
 await test('Missing Azubi standard price remains configurable in the material list',async()=>{await role('business','materials');assert.equal(await page.locator('form[data-form="hourly-price"] input[name="name"][value="Auszubildendenstunde"]').count(),1);});
 await test('An unavailable price sync blocks an open invoice rather than using an incorrect default',async()=>{assert.equal(await page.evaluate(id=>{const a=window.__appTest,o=a.state.rows.orders.find(x=>x.id===id),i=a.state.rows.items.find(x=>x.work_order_id===id&&x.position_name==='Monteurstunde');a.state.customerRatesReady=false;try{a.invoiceItemPrice(i,o);return false;}catch(e){return /Kundensätze/.test(e.message);}finally{a.state.customerRatesReady=true;}},order.id),true);});
 await test('Finalized invoices use stored prices regardless of newer customer rates',async()=>{const value=await page.evaluate(id=>{const a=window.__appTest,o={...a.state.rows.orders.find(x=>x.id===id),invoiced:true},i={...a.state.rows.items.find(x=>x.work_order_id===id&&x.position_name==='Monteurstunde'),unit_price:54};return a.invoiceItemPrice(i,o);},order.id);assert.equal(value,54);});
 await test('No browser runtime errors during customer editing, account settings or invoice generation',async()=>assert.deepEqual(errors,[]));
 await context.close();console.log(JSON.stringify({passed,production_writes:0,real_logins:0}));
 }finally{await browser.close();await queue;await db.close();await new Promise(r=>server.close(r));}
}
main().catch(e=>{console.error(e.stack);process.exitCode=1;});
