/* Real browser downloads and manager quotation UI with disposable PostgreSQL. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),os=require('node:os');
const {chromium}=require('playwright'),{PDFDocument}=require('pdf-lib'),{fixture}=require('./team-db-fixture.cjs');
const directory=path.resolve(__dirname,'../..');
const source=fs.readFileSync(path.join(directory,'app-v800.js'),'utf8').replace(/\}\)\(\);\s*$/,`window.__appTest={state,render,reload,timeAccountReport,offersFeature,planningPdfData};})();`);
const output=process.env.PDF_QA_OUTPUT_DIR||path.join(os.tmpdir(),'worktime-pdf-qa-v857');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{
  const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';
  if(name==='config.js'){res.setHeader('Content-Type','application/javascript');return res.end('window.WORKTIME_CONFIG={supabaseUrl:"https://test.invalid",supabasePublishableKey:"test"}');}
  if(name==='app-v800.js'){res.setHeader('Content-Type','application/javascript');return res.end(source);}
  if(name==='service-worker.js'){res.statusCode=404;return res.end();}
  const file=path.resolve(directory,name);if(!file.startsWith(directory+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end();}
  res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(file));
});
async function main(){
  const {db,ids,actor,admin}=await fixture({legacyRecords:true,offers:true,units:true,catalog:true});let current='business',queue=Promise.resolve(),passed=0,saveCalls=0,failSave=false,failOffers=false,failCatalog=false;const errors=[];
  await admin();await db.query('update customers set custom_fields=$1 where id=$2',[JSON.stringify({first_name:'Peter',street:'Teststraße',house_no:'12',postal_code:'44135',city:'Dortmund',email:'peter@example.test'}),ids.customer]);
  await db.query("insert into work_days(employee_id,work_date,sick) values($1,'2026-10-07',1)",[ids.anna]);
  await db.query("insert into vacation_requests(employee_id,start_date,end_date,status) values($1,'2026-10-08','2026-10-09','approved'),($1,'2026-10-14','2026-10-16','requested')",[ids.anna]);
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});
  try{
    const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Europe/Berlin',serviceWorkers:'block',acceptDownloads:true}),page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
    await context.route('**/*',route=>{
      const request=route.request(),url=new URL(request.url());if(url.hostname==='127.0.0.1')return route.continue();if(url.hostname!=='test.invalid')return route.abort();
      queue=queue.then(async()=>{
        const method=request.method(),body=request.postDataJSON(),send=(value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value,(key,value)=>['work_date','event_date','start_date','end_date','offer_date','valid_until'].includes(key)&&typeof value==='string'?value.slice(0,10):value)});
        try{
          await actor(current);
          if(url.pathname==='/functions/v1/mailbox-send'&&body.action==='recipients')return send({recipients:[]});
          if(url.pathname.includes('/rpc/')){
            const name=url.pathname.split('/').at(-1);
            if(name==='work_order_team_context')return send((await db.query('select work_order_team_context($1) result',[body.p_company])).rows[0].result);
            if(name==='current_business_branding')return send([{id:ids.business,company_name:'Elektro Test & Partner'}]);
            if(name==='save_offer_v857'){saveCalls++;if(failSave)return send({message:'Test: Verbindung unterbrochen'},503);return send((await db.query('select to_jsonb(save_offer_v857($1::jsonb,$2)) result',[JSON.stringify(body.p_data),body.p_revision])).rows[0].result);}
            if(name==='delete_offer_v857')return send((await db.query('select delete_offer_v857($1,$2) result',[body.p_id,body.p_revision])).rows[0].result);
            throw Error('Unexpected RPC '+name);
          }
          const table=url.pathname.split('/').at(-1),tables=['profiles','customers','appointments','planning_requests','mailbox_messages','work_days','vacation_requests','time_entries','work_orders','work_order_items','materials','work_order_documents','offers'];
          if(method!=='GET')throw Error('Unexpected mutation '+table);
          if(!tables.includes(table))return send([]);if(table==='offers'&&failOffers)return send({message:'Test: offline'},503);if(failCatalog&&['customers','materials'].includes(table))return send({message:'Test: Katalog vorübergehend offline'},503);
          const params=[],conditions=[];for(const [field,value] of url.searchParams)if(value.startsWith('eq.')&&/^[a-z_]+$/.test(field)){params.push(value.slice(3));conditions.push(field+'=$'+params.length);}
          const where=conditions.length?' where '+conditions.join(' and '):'',rows=(await db.query('select * from '+table+where+' limit '+Number(url.searchParams.get('limit')||1000)+' offset '+Number(url.searchParams.get('offset')||0),params)).rows;
          if(table==='profiles')rows.forEach(row=>{row.company_name=row.id===ids.otherBusiness?'Andere Firma':'Elektro Test & Partner';row.display_name={anna:'Anna Müller',max:'Max Meister',business:'Geschäftsleitung',admin:'Administrator'}[row.username]||row.username;});
          return send(rows);
        }catch(error){return send({message:error.message},400);}
      });return queue;
    });
    await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>!!window.__appTest);
    async function role(name,view='offers'){
      await queue;await admin();const profile=(await db.query('select * from profiles where id=$1',[ids[name]])).rows[0];current=name;profile.display_name=name==='anna'?'Anna Müller':name;profile.company_name='Elektro Test & Partner';
      await page.evaluate(async({profile,company,employee,view})=>{const app=window.__appTest;Object.assign(app.state,{profile,session:{user:{id:profile.id},access_token:'synthetic'},businessId:company,employeeId:employee,view,date:'2026-10-05',month:'2026-10',notice:null,menu:false,offerId:''});await app.reload();app.render();},{profile,company:ids.business,employee:ids.anna,view});
    }
    const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
    const form=()=>page.locator('form[data-form="offer"]');
    async function download(click,filename){const pending=page.waitForEvent('download');await click();const item=await pending;assert.match(item.suggestedFilename(),/\.pdf$/);const file=path.join(output,filename);await item.saveAs(file);const bytes=fs.readFileSync(file);assert.equal(bytes.subarray(0,5).toString(),'%PDF-');assert.ok((await PDFDocument.load(bytes)).getPageCount()>0);assert.equal(new URL(page.url()).hostname,'127.0.0.1');return file;}
    await role('business');
    await test('Offers appear only in the manager dropdown, not in employee accounts',async()=>{await page.locator('[data-action="menu"]').click();assert.equal(await page.locator('[data-action="nav"][data-view="offers"]').count(),1);await role('anna');await page.locator('[data-action="menu"]').click();assert.equal(await page.locator('[data-action="nav"][data-view="offers"]').count(),0);assert.match(await page.locator('h2').innerText(),/Angebote/);assert.equal(await page.locator('[data-action="offer-new"]').count(),0);await role('business');});
    await test('Selecting a company customer fills its address without affecting the keyboard focus',async()=>{await page.locator('[data-action="offer-new"]').click();await form().locator('[name="customer_name"]').fill('Klostermanns Hof');assert.equal(await form().locator('[name="customer_city"]').inputValue(),'Dortmund');assert.equal(await form().locator('[name="customer_street"]').inputValue(),'Teststraße');assert.equal(await page.evaluate(()=>document.activeElement.name),'customer_name');await form().locator('[name="title"]').fill('Installation mit Material & Arbeitsstunden');});
    await test('Material and labor prices populate from the company catalog; totals update immediately',async()=>{await form().locator('[data-offer-name]').fill('Kabel');assert.equal(await form().locator('[data-offer-price]').inputValue(),'2');await form().locator('[data-offer-quantity]').fill('3');await form().locator('[data-action="offer-add-labor"]').click();const labor=form().locator('[data-kind="labor"]');assert.equal(await labor.locator('[data-offer-name]').inputValue(),'Monteurstunde');assert.equal(await labor.locator('[data-offer-price]').inputValue(),'55');await labor.locator('[data-offer-quantity]').fill('2.25');await form().locator('[name="vat_rate"]').fill('19');assert.match(await form().locator('[data-offer-total]').innerText(),/154,40/);assert.equal(await page.evaluate(()=>document.activeElement.name),'vat_rate');});
    await test('Quotation units default from the catalog and permit an independent override without changing prices',async()=>{assert.deepEqual(await form().locator('[data-offer-unit]').first().locator('option').evaluateAll(nodes=>nodes.map(n=>n.textContent)),['Stk','M','H','Pau','Kg']);assert.equal(await form().locator('[data-kind="labor"] [data-offer-unit]').inputValue(),'H');await form().locator('[data-offer-unit]').first().selectOption('Kg');assert.match(await form().locator('[data-offer-total]').innerText(),/154,40/);});
    await test('Quotation layout stays within portrait, landscape and desktop screens',async()=>{for(const [width,height] of [[320,740],[390,844],[844,390],[1440,900]]){await page.setViewportSize({width,height});const bounds=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(bounds.scroll<=bounds.width+1,JSON.stringify(bounds));await page.screenshot({path:path.join(output,`Angebot_${width}x${height}.png`),fullPage:true});}await page.setViewportSize({width:390,height:844});});
    await test('Double save creates exactly one offer, immediately visible, and no work/time booking',async()=>{const before=saveCalls;await form().locator('button.primary').dblclick();await page.waitForFunction(()=>!!window.__appTest.state.offerId&&window.__appTest.state.offerId!=='new');assert.equal(saveCalls-before,1);assert.equal(await page.locator('#offer-list .row-card').count(),1);assert.match(await form().locator('[data-offer-status]').innerText(),/gespeichert/);await admin();assert.equal((await db.query('select count(*)::int n from work_orders')).rows[0].n,1);assert.equal((await db.query('select count(*)::int n from time_entries')).rows[0].n,2);});
    await test('Saved offer PDF is an actual on-device download and the app stays open',async()=>{assert.equal(await form().locator('[data-offer-unit]').first().inputValue(),'Kg');await download(()=>page.locator('#offer-editor [data-action="offer-pdf"]').click(),'Angebot_Material_Arbeitsstunden.pdf');});
    await test('Offer edits and number survive a re-render and synchronize on reload',async()=>{await form().locator('[name="notes"]').fill('Neue Notiz mit Leerzeichen');const number=await page.locator('#offer-editor .eyebrow').innerText();await page.evaluate(()=>window.__appTest.render());assert.equal(await form().locator('[name="notes"]').inputValue(),'Neue Notiz mit Leerzeichen');assert.equal(await page.locator('#offer-editor .eyebrow').innerText(),number);await form().locator('button.primary').click();await page.waitForFunction(()=>window.__appTest.state.rows.offers[0].revision===2);await page.evaluate(async()=>{await window.__appTest.reload();window.__appTest.render();});assert.equal(await form().locator('[name="notes"]').inputValue(),'Neue Notiz mit Leerzeichen');});
    await test('Failed saves preserve all input and failed reloads do not hide previously saved quotes',async()=>{failSave=true;await form().locator('[name="notes"]').fill('Nicht verlieren');await form().locator('button.primary').click();await page.waitForFunction(()=>document.querySelector('[data-offer-status]').textContent.includes('unterbrochen'));assert.equal(await form().locator('[name="notes"]').inputValue(),'Nicht verlieren');failSave=false;failOffers=true;await page.locator('[data-action="offer-refresh"]').click();await page.waitForFunction(()=>document.querySelector('[data-offer-status]').textContent.includes('synchronisiert'));assert.equal(await page.locator('#offer-list .row-card').count(),1);failOffers=false;});
    await test('Similarity confirmation reuses an existing customer rather than creating duplicate business data',async()=>{await page.locator('[data-action="offer-new"]').click();await form().locator('[name="customer_name"]').fill('Klostermann');await form().locator('[name="title"]').fill('Ähnlicher Kundenname');await form().locator('[data-offer-name]').fill('Kabel');page.once('dialog',dialog=>dialog.accept('1'));await form().locator('button.primary').click();await page.waitForFunction(()=>window.__appTest.state.rows.offers.length===2);assert.equal(await form().locator('[name="customer_name"]').inputValue(),'Klostermanns Hof');await admin();assert.equal((await db.query('select count(*)::int n from customers')).rows[0].n,2);});
    await test('Offer deletion is immediate, persists after reload, and does not remove work orders',async()=>{page.once('dialog',dialog=>dialog.accept());await page.locator('[data-action="offer-delete"]').click();await page.waitForFunction(()=>window.__appTest.state.rows.offers.length===1);await page.evaluate(async()=>{await window.__appTest.reload();window.__appTest.render();});assert.equal(await page.locator('#offer-list .row-card').count(),1);await admin();assert.equal((await db.query('select count(*)::int n from work_orders')).rows[0].n,1);});
    await test('Administrator changes between companies without leaking customers or offers',async()=>{await role('admin');const selector=page.locator('[data-select="business"]');await selector.selectOption(ids.otherBusiness);await page.waitForFunction(()=>window.__appTest.state.offersReady&&window.__appTest.state.rows.offers.length===0);assert.equal(await page.locator('#offer-list .row-card').count(),0);await page.locator('[data-action="offer-new"]').click();const options=await page.locator('#offer-customers option').evaluateAll(nodes=>nodes.map(node=>node.value));assert.deepEqual(options,['Anderer Kunde']);});
    await test('Employee yearly PDF downloads working times and absence-only dates, without a popup or navigation',async()=>{await role('anna','settings');assert.equal(await page.locator('[data-action="pdf"]').count(),1);assert.equal(await page.locator('[data-form="time-account-download"] [name="year"]').inputValue(),'2026');const pagesBefore=context.pages().length;await download(()=>page.locator('[data-form="time-account-download"] button').click(),'Jahresübersicht_2026.pdf');assert.equal(context.pages().length,pagesBefore,JSON.stringify(context.pages().map(tab=>tab.url())));assert.equal(await page.locator('[data-form="time-account-download"] button').isEnabled(),true);});
    await test('Planning date-range PDF remains a true on-device download',async()=>{await role('anna','planning');await page.locator('[data-action="plan-pdf-toggle"]').click();const planning=page.locator('[data-form="planning-pdf"]');await planning.locator('[name="from"]').fill('2026-10-01');await planning.locator('[name="to"]').fill('2026-10-31');await download(()=>planning.locator('button').click(),'Planung_Oktober_2026.pdf');});
    await test('Long yearly and offer PDFs include all rows across multiple pages with a prominent logo',async()=>{
      const result=await page.evaluate(async()=>{
        const canvas=document.createElement('canvas');canvas.width=600;canvas.height=200;const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,600,200);ctx.fillStyle='#b11328';ctx.font='bold 66px Arial';ctx.fillText('Elektro Test',115,125);ctx.fillStyle='#f0b900';ctx.fillRect(30,30,45,140);const logoBytes=Uint8Array.from(atob(canvas.toDataURL('image/png').split(',')[1]),c=>c.charCodeAt(0));
        const app=window.__appTest;let i=0;app.state.rows.entries=Array.from({length:60},(_,index)=>({id:'qa-'+index,employee_id:app.state.profile.id,work_date:'2026-10-'+String(5+Math.floor(index/4)).padStart(2,'0'),customer_name:'Auftrag '+(++i)+' - Langer Kundenname & Gebäudetechnik',start_time:'08:00',end_time:'09:00',pause_hours:0,executed_hours:1}));app.state.rows.orders=[];
        const year=app.timeAccountReport().years.find(row=>row.year==='2026'),annual=await window.DevicePdf.createTimeAccount({year,person:'Anna Müller',company:'Elektro Test & Partner',logoBytes});
        const items=Array.from({length:40},(_,index)=>({kind:index%3===0?'labor':'material',name:'Position '+(index+1)+' - Elektrische Montage & Gebäudetechnik mit besonders langer Materialbezeichnung',quantity:2.25,unit:index%3===0?'h':'Stk.',unit_price:55,line_total:123.75}));
        const quote=await window.DevicePdf.createOffer({company:'Elektro Test & Partner',logoBytes,offer:{offer_number:'ANG-2026-TEST',customer_name:'Klostermanns Hof',customer_snapshot:{street:'Teststraße',house_no:'12',city:'Dortmund',postal_code:'44135'},offer_date:'2026-10-05',valid_until:'2026-11-05',title:'Installation und Modernisierung',status:'ready',items,subtotal:4950,vat_rate:19,tax_amount:940.5,total:5890.5,notes:'Vielen Dank für Ihre Anfrage.\nBitte bestätigen Sie das Angebot schriftlich.'}});
        return {annual:Array.from(annual),quote:Array.from(quote)};
      });
      for(const [name,bytes] of Object.entries(result)){const file=path.join(output,name==='annual'?'Jahresübersicht_Langer_Monat_Logo.pdf':'Angebot_Lange_Positionen_Logo.pdf');fs.writeFileSync(file,Buffer.from(bytes));assert.ok((await PDFDocument.load(Buffer.from(bytes))).getPageCount()>1);console.log('PDF_QA_OUTPUT '+file);}
    });
    await test('Declining similar customer and article suggestions registers both in the company catalogs immediately',async()=>{
      await admin();await db.query("insert into customers(employee_id,name) values($1,'Kremer')",[ids.anna]);await db.query("insert into materials(business_id,name,unit_price,unit) values($1,'Döpke W16',7,'Stk'),($1,'Hager B16 Alt',10,'Stk')",[ids.business]);await role('business');await page.locator('[data-action="offer-new"]').click();
      await form().locator('[name="customer_name"]').fill('Krämer');await form().locator('[name="title"]').fill('Neuer Kunde und neuer Artikel');await form().locator('.offer-address summary').click();await form().locator('[name="customer_city"]').fill('Dortmund');await form().locator('[data-offer-name]').fill('Hager B16');await form().locator('[data-offer-price]').fill('14.5');await form().locator('[data-offer-unit]').selectOption('Stk');
      const choices=[];const decline=dialog=>{choices.push(dialog.message());return dialog.accept('0');};page.on('dialog',decline);await form().locator('button.primary').click();await page.waitForFunction(()=>window.__appTest.state.rows.offers.some(o=>o.customer_name==='Krämer'));await page.waitForFunction(()=>window.__appTest.state.rows.customers.some(c=>c.name==='Krämer')&&window.__appTest.state.rows.materials.some(m=>m.name==='Hager B16'));page.off('dialog',decline);
      assert.ok(choices.length>=2,JSON.stringify(choices));const records=await page.evaluate(()=>({customers:window.__appTest.state.rows.customers,materials:window.__appTest.state.rows.materials}));assert.equal(records.customers.filter(c=>c.name==='Krämer').length,1);assert.equal(records.customers.filter(c=>c.name==='Kremer').length,1);assert.equal(records.customers.find(c=>c.name==='Krämer').custom_fields.city,'Dortmund');assert.equal(Number(records.materials.find(m=>m.name==='Hager B16').unit_price),14.5);assert.match(await form().locator('[data-offer-status]').innerText(),/Stamm|stamm/);
    });
    await test('New quotation catalogs are shared with another employee account of the same business',async()=>{
      await role('anna','customers');const records=await page.evaluate(()=>({customers:window.__appTest.state.rows.customers,materials:window.__appTest.state.rows.materials}));assert.ok(records.customers.some(c=>c.name==='Krämer'));assert.ok(records.materials.some(m=>m.name==='Hager B16'));assert.ok(!records.customers.some(c=>c.name==='Anderer Kunde'));await role('business');
    });
    await test('Declining five article suggestions saves every new article, including articles without prices',async()=>{
      await page.locator('[data-action="offer-new"]').click();await form().locator('[name="customer_name"]').fill('Krämer');await form().locator('[name="title"]').fill('Fünf neue Artikel');
      for(let i=0;i<5;i++){if(i)await form().locator('[data-action="offer-add-material"]').click();const row=form().locator('[data-offer-line]').nth(i);await row.locator('[data-offer-name]').fill('Hager B16 Neu '+i);await row.locator('[data-offer-price]').fill('0');await row.locator('[data-offer-unit]').selectOption(i===4?'Kg':'Stk');}
      const choices=[];const decline=dialog=>{choices.push(dialog.message());return dialog.accept('0');};page.on('dialog',decline);await form().locator('button.primary').click();await page.waitForFunction(()=>window.__appTest.state.rows.materials.filter(m=>m.name.startsWith('Hager B16 Neu ')).length===5);page.off('dialog',decline);assert.equal(choices.length,5);assert.equal(await form().locator('[data-offer-line]').count(),5);assert.match(await form().locator('[data-offer-status]').innerText(),/gespeichert/);
    });
    await test('Catalog refresh failure after a successful save never loses or duplicates the offer',async()=>{
      await page.locator('[data-action="offer-new"]').click();await form().locator('[name="customer_name"]').fill('Krämer');await form().locator('[name="title"]').fill('Gespeichert trotz Listenfehler');await form().locator('[data-offer-name]').fill('Hager B16');const before=saveCalls;failCatalog=true;await form().locator('button.primary').click();await page.waitForFunction(()=>document.querySelector('[data-offer-status]')?.textContent.includes('Listen konnten'));assert.equal(saveCalls-before,1);assert.match(await form().locator('[data-offer-status]').innerText(),/^Angebot und Stammdaten wurden gespeichert/);assert.notEqual(await form().locator('[name="id"]').inputValue(),'');assert.equal(await page.evaluate(()=>Object.keys(sessionStorage).filter(key=>key.startsWith('zeiterfassung-offer-draft-v859:')).length),0);failCatalog=false;await role('business');await admin();assert.equal((await db.query("select count(*)::int n from offers where title='Gespeichert trotz Listenfehler'")).rows[0].n,1);
    });
    await test('Aborting similarity confirmation writes neither the offer nor a new customer/material',async()=>{
      await page.locator('[data-action="offer-new"]').click();await form().locator('[name="customer_name"]').fill('Krämer Abbruch');await form().locator('[name="title"]').fill('Nicht speichern');await form().locator('[data-offer-name]').fill('Hager B16 Abbruch');const before=saveCalls;page.once('dialog',dialog=>dialog.dismiss());await form().locator('button.primary').click();await page.waitForFunction(()=>document.querySelector('[data-offer-status]')?.textContent.includes('abgebrochen'));assert.equal(saveCalls,before);await admin();assert.equal((await db.query("select count(*)::int n from customers where name='Krämer Abbruch'")).rows[0].n,0);assert.equal((await db.query("select count(*)::int n from materials where name='Hager B16 Abbruch'")).rows[0].n,0);
    });
    await test('Explicitly confirming a deleted quotation customer/article as new registers fresh catalog IDs',async()=>{
      await admin();const old=(await db.query("select * from offers where title='Neuer Kunde und neuer Artikel'")).rows[0];await db.query('delete from customers where id=$1',[old.customer_id]);await db.query('delete from materials where id=$1',[old.items[0].material_id]);await role('business');await page.locator('[data-action="offer-open"][data-id="'+old.id+'"]').click();assert.equal(await form().locator('[name="customer_id"]').inputValue(),old.customer_id);
      const choices=[];const decline=dialog=>{choices.push(dialog.message());return dialog.accept('0');};page.on('dialog',decline);await form().locator('button.primary').click();await page.waitForFunction(()=>document.querySelector('[data-offer-status]')?.textContent.includes('gespeichert')&&!document.querySelector('form[data-form="offer"] button.primary')?.disabled);page.off('dialog',decline);assert.equal(choices.length,2);await admin();const saved=(await db.query('select * from offers where id=$1',[old.id])).rows[0];assert.ok(saved.customer_id&&saved.items[0].material_id);assert.notEqual(saved.customer_id,old.customer_id);assert.notEqual(saved.items[0].material_id,old.items[0].material_id);assert.equal(saved.items[0].unit_price,old.items[0].unit_price);assert.ok(await page.evaluate(()=>window.__appTest.state.rows.customers.some(c=>c.name==='Krämer')&&window.__appTest.state.rows.materials.some(m=>m.name==='Hager B16')));
    });
    assert.deepEqual(errors,[]);console.log(JSON.stringify({passed,productionWrites:0,runtimeErrors:0,pdfDirectory:output}));
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve));await db.close();}
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
