/* Synthetic photos/accounts only; browser -> actual PostgreSQL with RLS. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright'),{PDFDocument,StandardFonts}=require('pdf-lib'),{fixture}=require('./team-db-fixture.cjs');
const directory=path.resolve(__dirname,'../..'),source=fs.readFileSync(path.join(directory,'app-v800.js'),'utf8').replace(/\}\)\(\);\s*$/,'window.__deviceTest={state,render,reload,deviceFeatures,auth};})();');
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(name==='config.js'){res.setHeader('Content-Type','application/javascript');return res.end('window.WORKTIME_CONFIG={supabaseUrl:"https://test.invalid",supabasePublishableKey:"test"}');}if(name==='app-v800.js'){res.setHeader('Content-Type','application/javascript');return res.end(source);}if(name==='service-worker.js'){res.statusCode=404;return res.end();}const target=path.resolve(directory,name);if(!target.startsWith(directory+path.sep)||!fs.existsSync(target)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',/\.(m?js)$/.test(name)?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':name.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(fs.readFileSync(target));});
async function main(){const f=await fixture({offers:true,units:true}),{db,ids,actor,admin}=f;await db.exec('create role service_role bypassrls;');await db.exec(fs.readFileSync(path.join(directory,'supabase/migrations/20261008211721_device_features_v863.sql'),'utf8'));await db.exec(fs.readFileSync(path.join(directory,'supabase/migrations/20261009100224_appointment_reminders_v865.sql'),'utf8'));await db.exec(fs.readFileSync(path.join(directory,'supabase/migrations/20261009101042_arrival_timers_v865.sql'),'utf8'));let current='anna',queue=Promise.resolve(),passed=0,uploads=0,writes=0;const errors=[],requests=[],uploadFiles=[];
 await actor('anna');const shared=await f.save();const own=await f.save({...f.order,title:'Eigener Auftrag',work_date:'2026-10-02'},[f.periods[0]],[]);await actor('max');const maxOnly=await f.save({...f.order,employee_id:ids.max,title:'Nur Max',work_date:'2026-10-06'},[{...f.periods[0],employee_id:ids.max}],[]);
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});
 try{const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block',geolocation:{latitude:51.5,longitude:7,accuracy:10}});await context.grantPermissions(['geolocation'],{origin:url});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>requests.push(request.url()));page.on('dialog',dialog=>dialog.accept());
 await page.route('https://test.invalid/**',route=>{queue=queue.then(async()=>{const req=route.request(),u=new URL(req.url()),method=req.method(),body=req.headers()['content-type']?.includes('application/json')?req.postDataJSON():null;const send=(value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value,(key,value)=>['work_date','event_date','receipt_date','start_date','end_date'].includes(key)&&typeof value==='string'?value.slice(0,10):value)});try{await actor(current);if(u.pathname.includes('/storage/')){uploads++;uploadFiles.push({type:req.headers()['content-type'],bytes:req.postDataBuffer()});return send({id:'test-file'});}if(u.pathname.includes('/functions/'))return send({recipients:[]});if(u.pathname.includes('/rpc/')){const rpc=u.pathname.split('/').at(-1);if(rpc==='work_order_team_context')return send((await db.query('select work_order_team_context($1) result',[body.p_company])).rows[0].result);if(rpc==='current_business_branding')return send([{id:ids.business,company_name:'Testfirma'}]);return send(null);}const table=u.pathname.split('/').at(-1),allowed=['profiles','customers','appointments','planning_requests','mailbox_messages','work_days','vacation_requests','time_entries','work_orders','work_order_items','materials','work_order_documents','receipt_scans','company_notification_settings','push_subscriptions','customer_locations','order_arrivals','appointment_reminders','job_timers'];if(!allowed.includes(table))return send([]);const params=[],conditions=[];for(const [field,value]of u.searchParams)if(value.startsWith('eq.')&&/^[a-z_]+$/.test(field)){params.push(value.slice(3));conditions.push(field+'=$'+params.length);}const where=conditions.length?' where '+conditions.join(' and '):'';if(method==='GET'){const offset=Number(u.searchParams.get('offset')||0),limit=Number(u.searchParams.get('limit')||500);return send((await db.query('select * from '+table+where+' limit '+limit+' offset '+offset,params)).rows);}if(method==='POST'){writes++;const keys=Object.keys(body);return send((await db.query('insert into '+table+'('+keys.join(',')+') values('+keys.map((_,i)=>'$'+(i+1)).join(',')+') returning *',Object.values(body).map(value=>value&&typeof value==='object'?JSON.stringify(value):value))).rows);}if(method==='PATCH'){writes++;const keys=Object.keys(body);return send((await db.query('update '+table+' set '+keys.map((name,i)=>name+'=$'+(params.length+i+1)).join(',')+where+' returning *',[...params,...Object.values(body)])).rows);}if(method==='DELETE'){writes++;await db.query('delete from '+table+where,params);return send(null);}throw Error('Unexpected request');}catch(error){return send({message:error.message,code:error.code},400);}});return queue;});
 await page.goto(url);await page.waitForFunction(()=>!!window.__deviceTest);
 const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
 const role=async(name,view='customers',date='2026-10-05')=>{await queue;await admin();const profile=(await db.query('select * from profiles where id=$1',[ids[name]])).rows[0];current=name;await page.evaluate(async({profile,view,date,company,employee})=>{const a=window.__deviceTest;Object.assign(a.state,{profile,session:{user:{id:profile.id},access_token:'synthetic'},businessId:company,employeeId:profile.role==='employee'?profile.id:employee,view,date,month:date.slice(0,7),orderId:'',customerId:'',notice:null});await a.reload();a.render();},{profile,view,date,company:ids.business,employee:ids.anna});};
 await test('Save marks all missing login fields in red without sending credentials',async()=>{await page.locator('form[data-form="login"] button.primary').click();assert.equal(await page.locator('form[data-form="login"] [aria-invalid="true"]').count(),4);assert.equal(await page.locator('.form-error-summary').count(),1);assert.equal(writes,0);await page.locator('[name="username"]').fill('Felix van Eikelen');assert.equal(await page.locator('[name="username"]').getAttribute('aria-invalid'),null);});
 await test('Every login asks for a device persistence choice without default consent',async()=>{assert.equal(await page.locator('[name="remember_device"]').inputValue(),'');assert.match(await page.locator('form[data-form="login"]').innerText(),/auf diesem Gerät/);});
 await role('anna');
 await test('Customer shows own and shared work orders only, across all dates',async()=>{await page.locator('[data-action="customer"][data-id="'+ids.customer+'"]').click();assert.equal(await page.locator('.customer-order-list [data-action="open-order"]').count(),2);assert.equal(await page.locator('.customer-order-list [data-id="'+maxOnly.id+'"]').count(),0);});
 await test('Customer work-order card opens the full editable document immediately',async()=>{await page.locator('.customer-order-list [data-id="'+shared.id+'"]').click();assert.equal(await page.locator('form[data-form="order-edit"]').count(),1);assert.equal(await page.locator('[name="title"]').inputValue(),'Gemeinsame Montage');});
 await test('Scanner opens without replacing typed work-order notes or signature',async()=>{await page.locator('[name="documentation"]').fill('Notiz erhalten');const before=await page.locator('[name="signature_data"]').inputValue();await page.locator('[data-device-action="scan"]').click();assert.equal(await page.locator('dialog').count(),1);await page.locator('[data-device-action="scan-close"]').click();assert.equal(await page.locator('[name="documentation"]').inputValue(),'Notiz erhalten');assert.equal(await page.locator('[name="signature_data"]').inputValue(),before);});
 await test('Missing signature and customer are red and no work order is committed',async()=>{await role('anna','orders');await page.locator('[data-signature-submit]').click();assert.equal(await page.locator('[name="customer"]').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('.signature-pad').getAttribute('aria-invalid'),'true');});
 await role('business');
 await test('Business customer view includes all company work orders',async()=>{await page.locator('[data-action="customer"][data-id="'+ids.customer+'"]').click();assert.equal(await page.locator('.customer-order-list [data-action="open-order"]').count(),3);});
 await test('Only managers get the customer GPS setup; employees do not',async()=>{assert.equal(await page.locator('form[data-form="customer-location"]').count(),1);await role('anna');await page.locator('[data-action="customer"][data-id="'+ids.customer+'"]').click();assert.equal(await page.locator('form[data-form="customer-location"]').count(),0);});
 await role('anna','receipts');
 await test('Receipt scanner is available in Belege and the mobile layout stays inside the screen',async()=>{await page.locator('[data-device-action="scan"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('[name="scan_photo"]').getAttribute('capture'),'environment');});
 await test('Parser does not guess unknown/mixed tax rates or insert a material',async()=>{const parsed=await page.evaluate(()=>window.WorktimeDeviceFeatures.parseReceipt('Kabel 11,90\nMwSt 7 % 1,00\nMwSt 19 % 2,00\nSUMME 11,90'));assert.equal(parsed.items[0].net,null);assert.equal(parsed.gross,11.9);assert.equal(parsed.vatRate,null);});
 let image;
 await test('Real local German OCR reads a synthetic receipt without sending its image externally',async()=>{const b64=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=1100;canvas.height=1000;const c=canvas.getContext('2d');c.fillStyle='white';c.fillRect(0,0,1100,1000);c.fillStyle='black';c.font='42px Arial';['TEST QUITTUNG','Hager B16      11,90','Kabel         23,80','SUMME BRUTTO  35,70','NETTO         30,00','MwSt 19 %      5,70'].forEach((text,i)=>c.fillText(text,65,110+i*100));return canvas.toDataURL('image/png').split(',')[1];});image=Buffer.from(b64,'base64');const before=requests.length;await page.locator('[name="scan_photo"]').setInputFiles({name:'synthetic-receipt.png',mimeType:'image/png',buffer:image});await page.locator('[data-device-action="scan-recognize"]').click();await page.waitForFunction(()=>/Positionsvorschläge|manuell ergänzen|konnte/.test(document.querySelector('.scan-status').textContent),null,{timeout:120000});const text=await page.locator('[name="ocr_text"]').inputValue();assert.match(text,/Hager B16/);assert.equal(await page.locator('[name="gross_total"]').inputValue(),'35.70');assert.equal(await page.locator('[name="net_total"]').inputValue(),'30.00');assert.ok(requests.slice(before).every(request=>request.startsWith(url+'/')));});
 await test('Reviewed receipt uploads once and stores amounts without changing the material list',async()=>{const count=(await db.query('select count(*) count from materials')).rows[0].count;await page.locator('dialog [name="title"]').fill('Test Tankbeleg');await page.locator('dialog button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('.scan-status').textContent.includes('Beleg gespeichert'));assert.equal(uploads,1);assert.equal((await db.query('select count(*) count from materials')).rows[0].count,count);await page.locator('[data-device-action="scan-close"]').click();assert.match(await page.locator('.receipt-detail').first().innerText(),/Test Tankbeleg/);});
 await test('Deleting a receipt removes it from the list immediately',async()=>{await page.locator('.receipt-detail').first().locator('summary').click();await page.locator('[data-device-action="receipt-delete"]').click();await page.waitForFunction(()=>!document.querySelector('.receipt-detail'));});
 // Three disposable PDF fixtures: text, mixed scan/text and over-limit.
 const makePdf=async(scanned=false,overLimit=false)=>{
  const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);
  const first=pdf.addPage([600,600]);['TEST QUITTUNG','Hager B16      11,90'].forEach((text,i)=>first.drawText(text,{x:40,y:540-i*45,size:24,font}));
  if(overLimit){for(let i=1;i<21;i++)pdf.addPage([600,600]);}
  else if(scanned){
   const b64=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1100;c.height=800;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,1100,800);x.fillStyle='black';x.font='42px Arial';['TEST QUITTUNG SEITE 2','Kabel         23,80','SUMME BRUTTO  35,70','NETTO         30,00','MwSt 19 %      5,70'].forEach((text,i)=>x.fillText(text,65,110+i*100));return c.toDataURL('image/png').split(',')[1];});
   const image=await pdf.embedPng(Buffer.from(b64,'base64')),second=pdf.addPage([550,400]);second.drawImage(image,{x:0,y:0,width:550,height:400});
  }else{const second=pdf.addPage([600,600]);['TEST QUITTUNG SEITE 2','Kabel         23,80','SUMME BRUTTO  35,70','NETTO         30,00','MwSt 19 %      5,70'].forEach((text,i)=>second.drawText(text,{x:40,y:540-i*45,size:24,font}));}
  return Buffer.from(await pdf.save());
 };
 const digitalPdf=await makePdf(),mixedPdf=await makePdf(true),largePagesPdf=await makePdf(false,true);
 await role('anna','receipts');await page.locator('[data-device-action="scan"]').click();
 await test('PDF selection is separate from camera and does not upload during selection',async()=>{const count=uploads;assert.equal(await page.locator('[name="scan_pdf"]').getAttribute('accept'),'application/pdf,.pdf');await page.locator('[name="scan_pdf"]').setInputFiles({name:'Digitaler Beleg.pdf',mimeType:'application/pdf',buffer:digitalPdf});assert.equal(uploads,count);assert.equal(await page.locator('[name="scan_photo"]').inputValue(),'');assert.equal(await page.locator('[name="gross_total"]').inputValue(),'');assert.match(await page.locator('.scan-file-info').innerText(),/Digitaler Beleg.pdf/);});
 await test('Two-page text PDF extracts all articles and totals locally without OCR',async()=>{const count=uploads,before=requests.length;await page.locator('[data-device-action="scan-recognize"]').click();await page.waitForFunction(()=>document.querySelector('.scan-status').textContent.includes('alle 2 Seiten gelesen'),null,{timeout:60000});assert.equal(await page.locator('[name="gross_total"]').inputValue(),'35.70');assert.equal(await page.locator('[name="net_total"]').inputValue(),'30.00');assert.match(await page.locator('[name="ocr_text"]').inputValue(),/Hager B16/);assert.match(await page.locator('[name="ocr_text"]').inputValue(),/Kabel/);assert.equal(await page.locator('[name="scan_name"]').count(),2);assert.doesNotMatch(await page.locator('.scan-status').innerText(),/per Texterkennung/);assert.equal(uploads,count);assert.ok(requests.slice(before).every(request=>request.startsWith(url+'/')));await page.screenshot({path:process.env.PDF_SCAN_QA_IMAGE||path.join(directory,'tests/team/pdf-scan-v863-1.png')});});
 await test('Saving PDF preserves exact original bytes privately and adds no material',async()=>{const count=(await db.query('select count(*) count from materials')).rows[0].count;await page.locator('dialog [name="title"]').fill('PDF-Beleg geprüft');await page.locator('dialog button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('.scan-status').textContent.includes('Beleg gespeichert'));assert.equal(uploadFiles.at(-1).type,'application/pdf');assert.deepEqual(uploadFiles.at(-1).bytes,digitalPdf);assert.equal((await db.query('select count(*) count from materials')).rows[0].count,count);const row=(await db.query('select * from receipt_scans')).rows[0];assert.equal(row.file_name,'Digitaler Beleg.pdf');assert.equal(Number(row.gross_total),35.7);await page.locator('[data-device-action="scan-close"]').click();});
 await role('anna','orders');await page.evaluate(id=>{const a=window.__deviceTest;a.state.orderId=id;a.state.view='order-detail';a.render();},shared.id);
 await page.locator('[name="documentation"]').fill('Auftragsnotiz bleibt erhalten');await page.locator('[data-device-action="scan"]').click();
 await test('Mixed text/scanned PDF in work order uses real local OCR only for scanned page',async()=>{const before=requests.length,count=uploads;await page.locator('[name="scan_pdf"]').setInputFiles({name:'Gemischter Beleg.pdf',mimeType:'application/pdf',buffer:mixedPdf});await page.locator('[data-device-action="scan-recognize"]').click();await page.waitForFunction(()=>document.querySelector('.scan-status').textContent.includes('alle 2 Seiten gelesen'),null,{timeout:120000});assert.match(await page.locator('.scan-status').innerText(),/1 per Texterkennung/);assert.equal(await page.locator('[name="gross_total"]').inputValue(),'35.70');assert.equal(await page.locator('[name="net_total"]').inputValue(),'30.00');assert.equal(await page.locator('[name="scan_name"]').count(),2);assert.match(await page.locator('[name="ocr_text"]').inputValue(),/Kabel/);assert.equal(uploads,count);assert.ok(requests.slice(before).every(request=>request.startsWith(url+'/')));assert.equal(await page.locator('[name="documentation"]').inputValue(),'Auftragsnotiz bleibt erhalten');});
 await test('Scanned PDF is linked to its work order without altering working times',async()=>{await page.locator('dialog [name="title"]').fill('PDF zum Auftrag');const count=(await db.query('select count(*) count from time_entries')).rows[0].count;await page.locator('dialog button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('.scan-status').textContent.includes('Beleg gespeichert'));const row=(await db.query('select * from receipt_scans where work_order_id=$1',[shared.id])).rows[0];assert.equal(row.file_name,'Gemischter Beleg.pdf');assert.deepEqual(uploadFiles.at(-1).bytes,mixedPdf);assert.equal((await db.query('select count(*) count from time_entries')).rows[0].count,count);await page.locator('[data-device-action="scan-close"]').click();});
 await role('anna','receipts');await page.locator('[data-device-action="scan"]').click();
 await test('Broken PDF fails clearly without uploading or losing the scanner form',async()=>{const count=uploads;await page.locator('[name="scan_pdf"]').setInputFiles({name:'Defekt.pdf',mimeType:'application/pdf',buffer:Buffer.from('Not a PDF')});await page.locator('[data-device-action="scan-recognize"]').click();await page.waitForFunction(()=>document.querySelector('.scan-status').textContent.includes('keine lesbare PDF'));assert.equal(uploads,count);assert.equal(await page.locator('dialog form').count(),1);assert.equal(await page.locator('[name="scan_pdf"]').isEnabled(),true);});
 await test('Large-page PDF is not silently truncated and produces no write',async()=>{const count=uploads;await page.locator('[name="scan_pdf"]').setInputFiles({name:'21 Seiten.pdf',mimeType:'application/pdf',buffer:largePagesPdf});await page.locator('[data-device-action="scan-recognize"]').click();await page.waitForFunction(()=>document.querySelector('.scan-status').textContent.includes('höchstens 20 Seiten'),null,{timeout:60000});assert.equal(uploads,count);assert.equal(await page.locator('[name="ocr_text"]').inputValue(),'');assert.equal(await page.locator('[name="scan_pdf"]').isEnabled(),true);});
 await test('PDF helper groups amount columns and rejects unsupported or oversized files',async()=>{const result=await page.evaluate(()=>{const p=window.WorktimeReceiptPdf,lines=p.linesFromContent({items:[{str:'11,90',transform:[1,0,0,1,200,500],height:10},{str:'Hager B16',transform:[1,0,0,1,30,500],height:10},{str:'Netto 10,00',transform:[1,0,0,1,30,470],height:10}]});const errors=[];for(const f of [{name:'groß.pdf',type:'application/pdf',size:21*1024*1024},{name:'malware.exe',type:'application/octet-stream',size:10}])try{p.validateFile(f);}catch(e){errors.push(e.message);}return {lines,errors};});assert.equal(result.lines,'Hager B16 11,90\nNetto 10,00');assert.match(result.errors[0],/20 MB/);assert.match(result.errors[1],/Foto oder eine PDF/);await page.locator('[data-device-action="scan-close"]').click();});
 await role('business','settings');
 await test('Device consents exist on every account; reminder timing is no longer in settings',async()=>{assert.equal(await page.locator('[data-device-settings]').count(),1);assert.equal(await page.locator('form[data-form="notification-settings"]').count(),0);await role('admin','settings');assert.equal(await page.locator('form[data-form="notification-settings"]').count(),0);await role('anna','settings');assert.equal(await page.locator('[data-device-settings]').count(),1);assert.equal(await page.locator('form[data-form="notification-settings"]').count(),0);});
 await test('All layouts are usable in narrow portrait, landscape and desktop',async()=>{for(const size of [{width:320,height:720},{width:390,height:844},{width:844,height:390},{width:1440,height:900}]){await page.setViewportSize(size);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}});
 await page.setViewportSize({width:390,height:844});await role('business','customers');
 await test('Customer coordinates save without losing unsaved address edits',async()=>{await page.locator('[data-action="customer"][data-id="'+ids.customer+'"]').click();await page.locator('form[data-form="customer"] [name="street"]').fill('Nicht verlorene Straße');const form=page.locator('form[data-form="customer-location"]');await form.locator('[name="latitude"]').fill('51.5');await form.locator('[name="longitude"]').fill('7');await form.locator('button.primary').click();await page.waitForFunction(()=>document.querySelector('.location-status').textContent==='Gespeichert.');assert.equal(await page.locator('form[data-form="customer"] [name="street"]').inputValue(),'Nicht verlorene Straße');});
 await admin();const gpsDate=(await db.query("select (now() at time zone 'Europe/Berlin')::date::text as work_day")).rows[0].work_day;
 const gpsOrder=(await db.query("insert into work_orders(employee_id,work_date,customer_id,customer_name,title,start_time,end_time,pause_hours,executed_hours,calculation_mode) values($1,$2,$3,'Klostermanns Hof','GPS Prüfung','08:00','09:00',0,1,'end_time') returning *",[ids.anna,gpsDate,ids.customer])).rows[0];
 const openGps=async()=>{await role('anna','orders',gpsDate);await page.evaluate(id=>{const a=window.__deviceTest;a.state.orderId=id;a.state.view='order-detail';a.render();},gpsOrder.id);};
 await context.setGeolocation({latitude:52,longitude:7,accuracy:10});await openGps();
 await test('GPS stays off before personal settings consent; permission check stores no coordinates',async()=>{assert.match(await page.locator('.gps-status').innerText(),/ist aus/);assert.equal(await page.locator('[data-device-action="gps-watch"]').count(),0);await page.locator('[data-device-action="location-settings"]').click();const before=writes;await page.locator('[data-device-action="location-enable"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-device-action="location-disable"]'));assert.equal(writes,before);assert.equal((await db.query('select * from order_arrivals')).rows.length,0);});
 await openGps();
 await test('Consented foreground GPS starts on own today order; hiding app stops the watcher',async()=>{await page.waitForFunction(()=>document.querySelector('.gps-status').textContent.includes('Noch keine sichere Ankunft'));await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'));delete document.visibilityState;});assert.match(await page.locator('.gps-status').innerText(),/beendet/);await context.setGeolocation({latitude:51.5,longitude:7,accuracy:10});await queue;assert.equal((await db.query('select * from order_arrivals')).rows.length,0);});
 await test('Foreground GPS saves one arrival with server timestamp and no change to working hours',async()=>{const count=(await db.query('select count(*) count from time_entries')).rows[0].count;await page.locator('[data-device-action="gps-watch"]').click();await page.waitForFunction(()=>document.querySelector('.gps-status').textContent.includes('Ankunft gespeichert'));const rows=(await db.query('select * from order_arrivals')).rows;assert.equal(rows.length,1);assert.equal(rows[0].employee_id,ids.anna);assert.equal(rows[0].source,'proximity');assert.equal((await db.query('select count(*) count from time_entries')).rows[0].count,count);});
 if(process.env.DEVICE_QA_OUTPUT_DIR){fs.mkdirSync(process.env.DEVICE_QA_OUTPUT_DIR,{recursive:true});await role('anna','settings');for(const size of [{width:390,height:844},{width:844,height:390},{width:1440,height:900}]){await page.setViewportSize(size);await page.locator('[data-device-settings]').screenshot({path:path.join(process.env.DEVICE_QA_OUTPUT_DIR,'settings-'+size.width+'.png')});}}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed,runtimeErrors:errors.length,productionWrites:0,localOcr:true}));await context.close();
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));await db.close();}
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
