/* Native APIs are simulated locally; no real users, locations or push devices. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require('playwright');
const directory=path.resolve(__dirname,'../..');
const server=http.createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/device.js'?'application/javascript; charset=utf-8':'text/html; charset=utf-8');res.end(req.url==='/device.js'?fs.readFileSync(path.join(directory,'device-features-v863.js')):'<!doctype html><html><meta charset="utf-8"><div id="root"></div><script src="/device.js"></script></html>');});
async function main(){let passed=0;await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});
 try{const page=await browser.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:'+server.address().port);
 await page.evaluate(async()=>{
  const root=document.querySelector('#root'),state={profile:{id:'user-one'},view:'settings',rows:{orders:[],people:[]}},trace=[],rows=[],bindings=[];
  let nativeSub=null,permission='default',saveConfirmed=true,provider={sent:1,code:'accepted'},workerReady=true,geoError=0,geoCallback=null;
  const subscription={endpoint:'https://web.push.apple.com/synthetic',toJSON:()=>({endpoint:'https://web.push.apple.com/synthetic',keys:{p256dh:'synthetic',auth:'synthetic'}}),unsubscribe:async()=>{trace.push('unsubscribe');nativeSub=null;return true;}};
  const registration={active:{},pushManager:{getSubscription:async()=>nativeSub,subscribe:async()=>{trace.push(['subscribe',navigator.userActivation.isActive]);nativeSub=subscription;return nativeSub;}}};
  const notification={get permission(){return permission;},requestPermission:async()=>{trace.push(['permission',navigator.userActivation.isActive]);permission='granted';return permission;}};
  Object.defineProperty(window,'Notification',{configurable:true,value:notification});Object.defineProperty(window,'PushManager',{configurable:true,value:function(){}});
  Object.defineProperty(navigator,'serviceWorker',{configurable:true,value:{getRegistration:async()=>workerReady?registration:null,addEventListener(){}}});
  const geo={getCurrentPosition:(ok,fail)=>{trace.push('geo-permission');geoError?fail({code:geoError}):ok({coords:{latitude:51,longitude:7,accuracy:10}});},watchPosition(ok){trace.push('watch');geoCallback=ok;return 1;},clearWatch(){trace.push('clear-watch');}};
  Object.defineProperty(navigator,'geolocation',{configurable:true,value:geo});
  Object.defineProperty(navigator,'permissions',{configurable:true,value:{query:async()=>{throw Error('Safari fallback');}}});
  const render=()=>{root.innerHTML='<main class="content">'+(state.view==='order-detail'?'<form data-form="order-edit"><input name="id" value="synthetic-order"></form>':'')+'</main>';feature.afterRender();};
  const ctx={root,state,api:async(url,options)=>{trace.push(['api',url,options?.body]);if(url.includes('set_work_device_context')){const p=options.body;if(!p.p_employee){bindings.splice(0);return null;}const row={id:p.p_device,employee_id:p.p_employee,owner_id:state.profile.id,business_id:'work-company',subscription_id:p.p_subscription};bindings.splice(0,bindings.length,row);return row;}return url.includes('public-key')?{publicKey:btoa(String.fromCharCode(4,...Array(64).fill(7))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}:provider;},
   allRows:async(table)=>table==='work_device_contexts'?bindings:table==='push_subscriptions'?rows.filter(row=>row.user_id===state.profile.id):table==='customer_locations'?[{customer_id:'synthetic-customer',latitude:51,longitude:7,radius_m:150}]:[],write:async(table,payload)=>{trace.push(['write',table]);if(!saveConfirmed)return [];const row={id:'00000000-0000-4000-8000-000000000001',...payload};rows.splice(0,rows.length,row);return [row];},remove:async()=>{trace.push('remove');rows.splice(0);},render,businessId:()=>'',workerId:()=>state.profile.id,isManager:()=>false,isAdmin:()=>state.profile?.role==='administrator',orderForEmployee:()=>true,orderHours:()=>1,dateText:String,timeText:String,h:String};
  const feature=WorktimeDeviceFeatures.create(ctx);
  window.testDevice={state,trace,rows,feature,render,geoLate:()=>geoCallback?.({coords:{latitude:51,longitude:7,accuracy:10}}),clear:()=>trace.splice(0),set:values=>{if('permission'in values)permission=values.permission;if('saveConfirmed'in values)saveConfirmed=values.saveConfirmed;if('provider'in values)provider=values.provider;if('nativeSub'in values)nativeSub=values.nativeSub?subscription:null;if('workerReady'in values)workerReady=values.workerReady;if('geoError'in values)geoError=values.geoError;},reload:async()=>{await feature.load();render();}};
  await feature.load();render();
 });
 const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
 const wait=()=>page.waitForFunction(()=>!document.querySelector('[data-device-action="push-enable"]').disabled);
 const trace=()=>page.evaluate(()=>testDevice.trace);
 await test('Startup prepares push but never asks for notification or GPS permission',async()=>{assert.equal((await trace()).some(x=>x==='geo-permission'||Array.isArray(x)&&['subscribe','permission','write'].includes(x[0])),false);assert.equal(await page.locator('[data-device-action="location-disable"]').count(),0);});
 await test('One click grants and subscribes directly in a user gesture; row is confirmed',async()=>{await page.evaluate(()=>testDevice.clear());await page.locator('[data-device-action="push-enable"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-device-action="push-test"]'));const t=await trace();assert.deepEqual(t.slice(0,2),[['permission',true],['subscribe',true]]);assert.match(await page.locator('.device-status').innerText(),/aktiviert/);});
 await test('Test sends only current device and distinguishes provider acceptance from display',async()=>{await page.locator('[data-device-action="push-test"]').click();await wait();assert.match(await page.locator('.device-status').innerText(),/angenommen.*Mitteilungszentrale/s);const api=(await trace()).filter(x=>Array.isArray(x)&&x[0]==='api'&&x[1].includes('action=test')).at(-1);assert.deepEqual(api[2],{subscription_id:'00000000-0000-4000-8000-000000000001'});});
 await test('Reload retains existing permission and does not repeat subscribe or permission prompt',async()=>{await page.evaluate(async()=>{testDevice.clear();await testDevice.reload();});assert.equal(await page.locator('[data-device-action="push-test"]').count(),1);assert.equal((await trace()).some(x=>Array.isArray(x)&&['subscribe','permission'].includes(x[0])),false);});
 await test('Disabled stale server subscription is retired before a new permission-click registration',async()=>{await page.evaluate(async()=>{testDevice.clear();testDevice.rows[0].enabled=false;await testDevice.reload();});assert.equal((await trace()).includes('unsubscribe'),true);assert.equal(await page.locator('[data-device-action="push-test"]').count(),0);await page.locator('[data-device-action="push-enable"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-device-action="push-test"]'));});
 await test('Native subscription alone does not falsely indicate server registration',async()=>{await page.evaluate(async()=>{testDevice.rows.splice(0);await testDevice.reload();});assert.equal(await page.locator('[data-device-action="push-test"]').count(),0);assert.match(await page.locator('.device-badge').first().innerText(),/Registrierung.*aktivieren/);});
 await test('Unconfirmed server write stays inactive and reports the actual failure',async()=>{await page.evaluate(()=>testDevice.set({saveConfirmed:false}));await page.locator('[data-device-action="push-enable"]').click();await wait();assert.equal(await page.locator('[data-device-action="push-test"]').count(),0);assert.match(await page.locator('.device-status').innerText(),/nicht bestätigt/);await page.evaluate(()=>testDevice.set({saveConfirmed:true}));await page.locator('[data-device-action="push-enable"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-device-action="push-test"]'));});
 await test('Expired server device is unsubscribed and can be registered again',async()=>{await page.evaluate(()=>testDevice.set({provider:{sent:0,code:'device_expired'}}));await page.locator('[data-device-action="push-test"]').click();await wait();assert.equal(await page.locator('[data-device-action="push-test"]').count(),0);assert.match(await page.locator('.device-status').innerText(),/abgelaufen/);await page.evaluate(()=>testDevice.set({provider:{sent:1,code:'accepted'}}));await page.locator('[data-device-action="push-enable"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-device-action="push-test"]'));});
 await test('Disable removes current server registration before unsubscribing device',async()=>{await page.evaluate(()=>testDevice.clear());await page.locator('[data-device-action="push-disable"]').click();await wait();assert.deepEqual((await trace()).filter(x=>typeof x==='string'),['remove','unsubscribe']);assert.equal(await page.locator('[data-device-action="push-test"]').count(),0);});
 await test('Blocked native notifications show corrective instructions without prompting again',async()=>{await page.evaluate(async()=>{testDevice.clear();testDevice.set({permission:'denied'});await testDevice.reload();});await page.locator('[data-device-action="push-enable"]').click();await wait();assert.match(await page.locator('.device-status').innerText(),/blockiert/);assert.equal((await trace()).some(x=>Array.isArray(x)&&x[0]==='permission'),false);});
 await test('Cold worker reports preparation, not permission success, and never loses gesture to a network await',async()=>{await page.evaluate(async()=>{testDevice.clear();testDevice.set({permission:'default',workerReady:false});await testDevice.reload();});await page.locator('[data-device-action="push-enable"]').click();await wait();assert.match(await page.locator('.device-status').innerText(),/vorbereitet/);assert.equal((await trace()).some(x=>Array.isArray(x)&&x[0]==='permission'),false);await page.evaluate(()=>testDevice.set({workerReady:true}));await page.locator('[data-device-action="push-enable"]').click();await wait();assert.match(await page.locator('.device-status').innerText(),/nochmals/);await page.locator('[data-device-action="push-enable"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-device-action="push-test"]'));await page.locator('[data-device-action="push-disable"]').click();await wait();});
 await test('Location settings request once, persist only account-scoped consent, upload no coordinates',async()=>{await page.evaluate(()=>testDevice.clear());await page.locator('[data-device-action="location-enable"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-device-action="location-disable"]'));assert.deepEqual(await trace(),['geo-permission']);const stored=await page.evaluate(()=>Object.fromEntries(Object.entries(localStorage)));assert.deepEqual(stored,{'worktime-v864-location.user-one':'allowed'});assert.match(await page.locator('.location-permission-status').innerText(),/kein Standort hochgeladen/);});
 await test('Consent survives reload without another GPS request but not another account',async()=>{await page.evaluate(async()=>{testDevice.clear();await testDevice.reload();});assert.equal(await page.locator('[data-device-action="location-disable"]').count(),1);assert.equal((await trace()).includes('geo-permission'),false);await page.evaluate(async()=>{testDevice.state.profile={id:'user-two'};await testDevice.reload();});assert.equal(await page.locator('[data-device-action="location-disable"]').count(),0);assert.equal(await page.locator('[data-device-action="push-test"]').count(),0);});
 await test('Location disable revokes remembered consent immediately and denied GPS grants nothing',async()=>{await page.evaluate(async()=>{testDevice.state.profile={id:'user-one'};await testDevice.reload();});await page.locator('[data-device-action="location-disable"]').click();assert.equal(await page.evaluate(()=>localStorage.getItem('worktime-v864-location.user-one')),null);await page.evaluate(()=>testDevice.set({geoError:1}));await page.locator('[data-device-action="location-enable"]').click();await page.waitForFunction(()=>document.querySelector('.location-permission-status').textContent.includes('nicht erteilt'));assert.equal(await page.locator('[data-device-action="location-disable"]').count(),0);});
 await test('Revocation clears active watcher immediately and rejects an already queued location callback',async()=>{await page.evaluate(()=>testDevice.set({geoError:0}));await page.locator('[data-device-action="location-enable"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-device-action="location-disable"]'));await page.evaluate(()=>{const a=testDevice,date=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());a.state.rows.orders=[{id:'synthetic-order',customer_id:'synthetic-customer',work_date:date}];a.state.orderId='synthetic-order';a.state.view='order-detail';a.clear();a.render();});assert.equal((await trace()).includes('watch'),true);await page.evaluate(()=>{const b=document.createElement('button');b.dataset.deviceAction='location-disable';document.querySelector('#root').append(b);b.click();testDevice.geoLate();});assert.equal((await trace()).includes('clear-watch'),true);assert.equal((await trace()).some(x=>Array.isArray(x)&&x[0]==='write'),false);});
 await page.evaluate(async()=>{const a=testDevice;a.state.profile={id:'admin-one',role:'administrator'};a.state.view='settings';a.state.rows.people=[{id:'work-company',role:'business',company_name:'Testfirma'},{id:'work-user',role:'employee',business_id:'work-company',username:'Ich selbst'}];a.set({permission:'granted',workerReady:true,geoError:0});await a.reload();a.clear();});
 await test('Administrator GPS cannot be enabled before explicit personal work-account binding',async()=>{await page.locator('[data-device-action="location-enable"]').click();await wait();assert.match(await page.locator('.location-permission-status').innerText(),/Arbeitskonto.*verknüpfen/);assert.equal((await trace()).includes('geo-permission'),false);});
 await page.locator('[name="work_employee"]').selectOption('work-user');await page.locator('form[data-form="work-device-context"] button.primary').click();await page.waitForFunction(()=>document.querySelector('.work-context-status').textContent.includes('gespeichert'));
 await test('Administrator push registration uses real login and binds same device to own work employee',async()=>{await page.evaluate(()=>testDevice.clear());await page.locator('[data-device-action="push-enable"]').click();await page.waitForFunction(()=>!!document.querySelector('[data-device-action="push-test"]'));const t=await trace(),binding=t.find(x=>Array.isArray(x)&&x[0]==='api'&&x[1].includes('set_work_device_context'));assert.equal(binding[2].p_employee,'work-user');assert.equal(binding[2].p_subscription,'00000000-0000-4000-8000-000000000001');assert.equal(await page.evaluate(()=>testDevice.rows[0].user_id),'admin-one');});
 await test('Administrator GPS consent is work-account/device scoped; employee view selection leaves binding intact',async()=>{await page.locator('[data-device-action="location-enable"]').click();await page.waitForSelector('[data-device-action="location-disable"]');assert.equal(await page.evaluate(()=>localStorage.getItem('worktime-v864-location.admin-one.work-user')),'allowed');await page.evaluate(async()=>{testDevice.state.employeeId='another-person';await testDevice.reload();});assert.equal(await page.locator('[name="work_employee"]').inputValue(),'work-user');assert.equal(await page.locator('[data-device-action="push-test"]').count(),1);await page.locator('[name="work_employee"]').selectOption('');await page.locator('form[data-form="work-device-context"] button.primary').click();await page.waitForFunction(()=>document.querySelector('.work-context-status').textContent.includes('getrennt'));assert.equal(await page.locator('[data-device-action="location-disable"]').count(),0);assert.equal(await page.evaluate(()=>localStorage.getItem('worktime-v864-location.admin-one.work-user')),null);});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed,runtimeErrors:errors.length,productionRequests:0}));
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
