const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module');
const text=fs.readFileSync(path.resolve(__dirname,'../../supabase/functions/appointment-reminders/index.ts'),'utf8').replace("import webpush from 'npm:web-push@3.6.7';",'const webpush=TEST_WEBPUSH;');
const source=stripTypeScriptTypes(text,{mode:'strip'});
async function main(){let handler,userExists=true,pushFailure=0,passed=0,due=[],subscriptions=[],sent=[],queries=[];
 const response=data=>new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}});
 const env={SUPABASE_URL:'https://test.invalid',SUPABASE_SERVICE_ROLE_KEY:'synthetic-service',WORKTIME_VAPID_PUBLIC:'synthetic-public',WORKTIME_VAPID_PRIVATE:'synthetic-private',WORKTIME_PUSH_CRON_SECRET:'synthetic-cron'};
 vm.runInNewContext(source,{Deno:{env:{get:name=>env[name]},serve:fn=>handler=fn},TEST_WEBPUSH:{sendNotification:async(subscription,payload,options)=>{if(pushFailure)throw {statusCode:pushFailure};sent.push({subscription,payload:JSON.parse(payload),options});return {statusCode:201};}},URL,Response,JSON,Date,AbortSignal,fetch:async(url,options)=>{queries.push({url,options});if(url.includes('/auth/v1/user'))return options.headers.Authorization==='Bearer valid'?response({id:'anna'}):new Response('{}',{status:401});if(url.includes('/profiles?'))return response(userExists?[{id:'anna'}]:[]);if(url.includes('push_subscriptions?')&&options.method==='GET')return response(subscriptions);if(url.includes('claim_appointment_push_v863'))return response(due);return response([]);}});
 const test=async(name,fn)=>{queries=[];sent=[];await fn();passed++;console.log('PASS '+name);};
 const call=(action,headers={},method='POST')=>handler(new Request('https://test.invalid/functions/v1/appointment-reminders'+(action?'?action='+action:''),{method,headers}));
 const subscription={id:'subscription-anna',endpoint:'https://fcm.googleapis.com/fcm/send/synthetic',p256dh:'A'.repeat(87),auth:'B'.repeat(22)};
 await test('Public key requires a valid live profile and never returns private server secrets',async()=>{assert.equal((await call('public-key',{},'GET')).status,401);const result=await call('public-key',{Authorization:'Bearer valid'},'GET');assert.deepEqual(await result.json(),{publicKey:'synthetic-public'});userExists=false;assert.equal((await call('public-key',{Authorization:'Bearer valid'},'GET')).status,401);userExists=true;});
 await test('Normal user and anonymous keys cannot trigger cron-wide delivery',async()=>{for(const headers of [{},{Authorization:'Bearer valid'},{apikey:'synthetic-public'}])assert.equal((await call('',headers)).status,401);assert.equal(sent.length,0);});
 await test('Test sends only the authenticated user subscriptions and uses generic lock-screen content',async()=>{subscriptions=[subscription];const result=await call('test',{Authorization:'Bearer valid'});assert.equal((await result.json()).sent,1);assert.ok(queries.some(query=>query.url.endsWith('user_id=eq.anna')));assert.equal(sent[0].payload.title,'Zeiterfassung');assert.doesNotMatch(JSON.stringify(sent[0].payload),/Anna|Klostermann|Monteur|customer/i);assert.equal(sent[0].options.vapidDetails.privateKey,'synthetic-private');});
 await test('Scheduled delivery acknowledges only a successful push and restricts its row',async()=>{due=[{...subscription,appointment_id:'plan-one',subscription_id:subscription.id,scheduled_at:'2026-10-09T06:00:00Z'}];const result=await call('',{'x-worktime-cron':'synthetic-cron'});assert.equal((await result.json()).sent,1);assert.ok(queries.some(query=>query.url.includes('push_deliveries?appointment_id=eq.plan-one&subscription_id=eq.subscription-anna')&&query.options.method==='PATCH'));assert.equal(sent[0].payload.data.view,'planning');});
 await test('SSRF and lookalike push endpoints are not fetched or marked as sent',async()=>{for(const endpoint of ['https://fcm.googleapis.com.evil.test/send','https://fcmXgoogleapis.com/a','https://localhost/a','https://web.push.apple.com@evil.test/a']){due=[{...subscription,endpoint}];const result=await call('',{'x-worktime-cron':'synthetic-cron'});assert.equal((await result.json()).invalid,1);}assert.equal(sent.length,0);});
 await test('Expired device subscriptions are disabled; temporary errors stay retryable',async()=>{due=[{...subscription,subscription_id:subscription.id}];pushFailure=410;assert.equal((await (await call('',{'x-worktime-cron':'synthetic-cron'})).json()).expired,1);assert.ok(queries.some(query=>query.url.endsWith('push_subscriptions?id=eq.subscription-anna')&&query.options.body==='{"enabled":false}'));queries=[];pushFailure=503;assert.equal((await (await call('',{'x-worktime-cron':'synthetic-cron'})).json()).retry,1);assert.equal(queries.some(query=>query.options.method==='PATCH'),false);pushFailure=0;});
 console.log(JSON.stringify({passed,productionRequests:0}));
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
