const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const app=fs.readFileSync(path.resolve(__dirname,'../../app-v800.js'),'utf8');
const source=app.slice(app.indexOf('  function createSessionAuth('),app.indexOf('  /* END SESSION AUTH V859 */'))+'\nwindow.makeAuth=createSessionAuth;';
const store=()=>{const map=new Map();return {getItem:key=>map.get(key)||null,setItem:(key,value)=>map.set(key,String(value)),removeItem:key=>map.delete(key)};};
const fresh=label=>({user:{id:'test-user'},access_token:'test-'+label,refresh_token:'refresh-'+label,expires_at:Date.now()/1000+3600});
function environment(local=store(),transient=store(),initial=null){let current=initial,calls=0;const scope={window:{},localStorage:local,Headers,Date,atob,navigator:{},fetch:async()=>{calls++;return new Response(JSON.stringify(fresh('renewed')),{status:200,headers:{'Content-Type':'application/json'}});}};vm.runInNewContext(source,scope);return {local,transient,auth:scope.window.makeAuth({base:'https://test.invalid',key:'test',storage:'session',transientStore:transient,getSession:()=>current,setSession:value=>current=value}),get:()=>current,calls:()=>calls};}
async function main(){let passed=0;const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
 await test('Remember yes persists tokens only on this browser/device',()=>{const e=environment();e.auth.install(fresh('login'),true);assert.equal(JSON.parse(e.local.getItem('session')).remember_device,true);assert.equal(e.transient.getItem('session'),null);assert.equal(environment().local.getItem('session'),null);assert.equal('password' in JSON.parse(e.local.getItem('session')),false);});
 await test('Remember no uses session storage, not durable local storage',()=>{const e=environment();e.auth.install(fresh('login'),false);assert.equal(e.local.getItem('session'),null);assert.equal(JSON.parse(e.transient.getItem('session')).remember_device,false);assert.equal(environment(e.local).transient.getItem('session'),null);});
 await test('Token renewal keeps a non-persistent session non-persistent',async()=>{const e=environment(),old=fresh('old');old.expires_at=Date.now()/1000-10;e.auth.install(old,false);await e.auth.ensure();assert.equal(e.calls(),1);assert.equal(e.get().remember_device,false);assert.equal(e.local.getItem('session'),null);assert.equal(JSON.parse(e.transient.getItem('session')).refresh_token,'refresh-renewed');});
 await test('A remembered login survives a new page and preserves persistence on refresh',async()=>{const e=environment(),old=fresh('old');old.expires_at=Date.now()/1000-10;e.auth.install(old,true);const next=environment(e.local,store(),JSON.parse(e.local.getItem('session')));await next.auth.ensure();assert.equal(next.get().remember_device,true);assert.equal(next.transient.getItem('session'),null);});
 await test('Changing account or login choice removes the earlier durable session',()=>{const e=environment();e.auth.install(fresh('yes'),true);e.auth.install(fresh('no'),false);assert.equal(e.local.getItem('session'),null);e.auth.install(fresh('yes-again'),true);assert.equal(e.transient.getItem('session'),null);assert.equal(JSON.parse(e.local.getItem('session')).access_token,'test-yes-again');});
 await test('Logout removes both session stores and the legacy remembered login',()=>{const e=environment();e.auth.install(fresh('yes'),true);e.transient.setItem('session','stale');e.local.setItem('zeiterfassung-session-v700','legacy');e.auth.clear();assert.equal(e.get(),null);assert.equal(e.local.getItem('session'),null);assert.equal(e.transient.getItem('session'),null);assert.equal(e.local.getItem('zeiterfassung-session-v700'),null);});
 console.log(JSON.stringify({passed,productionRequests:0}));
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
