const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
async function main(){
 const text=fs.readFileSync(path.resolve(__dirname,'../../supabase/functions/customer-geocoding/handler.js'),'utf8');
 const {makeGeocodingHandler,normalizeCandidates}=await import('data:text/javascript;base64,'+Buffer.from(text).toString('base64'));
 let passed=0,providerCalls=[],rpcCalls=[],authorized=true,mode='fetch',providerError=false,key='synthetic-secret';
 const customer='00000000-0000-4000-8000-000000000007',hit={lat:51.5,lon:7,country_code:'de',formatted:'Teststraße 1',result_type:'building',rank:{confidence:1}};
 const handler=makeGeocodingHandler({key:()=>key,authenticate:async t=>authorized&&t==='valid'?'actor':null,rpc:async(name,args)=>{rpcCalls.push({name,args});if(mode==='denied')throw {code:'42501'};if(mode==='limited')throw {code:'P0001'};return name.startsWith('claim')?{status:mode,lease:'lease',address_key:'key',address:{street:'Teststraße',housenumber:'1',city:'Testort',postcode:'12345',country:'Germany'},candidates:[hit]}:{status:'ready',candidates:args.p_candidates,address_key:'key'};},fetchProvider:async(url,options)=>{providerCalls.push({url,options});if(providerError)throw Error('must not leak synthetic-secret');return Response.json({results:[hit,{...hit,country_code:'us'}]});}});
 const call=(body={customer_id:customer},headers={Authorization:'Bearer valid'},method='POST')=>handler(new Request('https://test.invalid/functions/customer-geocoding',{method,headers,body:['POST','PUT'].includes(method)?JSON.stringify(body):undefined}));
 const test=async(name,fn)=>{providerCalls=[];rpcCalls=[];mode='fetch';providerError=false;authorized=true;key='synthetic-secret';await fn();passed++;console.log('PASS '+name);};
 await test('Anonymous, invalid or deleted user cannot consume a provider request',async()=>{for(const headers of [{},{Authorization:'Bearer bad'}])assert.equal((await call(undefined,headers)).status,401);authorized=false;assert.equal((await call()).status,401);assert.equal(providerCalls.length,0);});
 await test('Method, CORS and oversized/malformed bodies fail closed',async()=>{assert.equal((await call(undefined,undefined,'GET')).status,405);assert.equal((await call(undefined,{Authorization:'Bearer valid',Origin:'https://evil.test'})).status,403);assert.equal((await call({customer_id:'invalid'})).status,400);assert.equal((await call({customer_id:customer,text:'x'.repeat(3000)})).status,400);assert.equal(providerCalls.length,0);});
 await test('Provider key missing and role/tenant denial give safe errors',async()=>{key='';assert.equal((await call()).status,503);key='synthetic-secret';mode='denied';assert.equal((await call()).status,403);mode='limited';assert.equal((await call()).status,429);assert.equal(providerCalls.length,0);});
 await test('Only server address components go to fixed Geoapify HTTPS endpoint',async()=>{const response=await call({customer_id:customer,company_id:'foreign',name:'PRIVATE',street:'EVIL',email:'PRIVATE'});assert.equal(response.status,200);assert.equal(providerCalls.length,1);const url=new URL(providerCalls[0].url);assert.equal(url.origin,'https://api.geoapify.com');assert.equal(url.searchParams.get('street'),'Teststraße');assert.equal(url.searchParams.get('name'),null);assert.equal(url.searchParams.get('email'),null);assert.equal(url.searchParams.get('filter'),'countrycode:de');assert.equal(providerCalls[0].options.redirect,'error');assert.equal(rpcCalls[0].args.p_actor,'actor');assert.doesNotMatch(await response.text(),/synthetic-secret|PRIVATE|lease/);});
 await test('Cached, pending, incomplete or stale result never fetches again',async()=>{for(const value of ['ready','pending','incomplete','stale']){mode=value;assert.equal((await (await call()).json()).status,value);}assert.equal(providerCalls.length,0);});
 await test('Provider errors never reveal URLs or tokens and record retry state',async()=>{providerError=true;const r=await call();assert.equal(rpcCalls.at(-1).args.p_error,true);assert.deepEqual(rpcCalls.at(-1).args.p_candidates,[]);assert.doesNotMatch(await r.text(),/synthetic-secret|apiKey|https/);});
 await test('Invalid/foreign/nonfinite coordinates are ignored and results bounded',async()=>{const rows=normalizeCandidates({results:[{...hit,lat:NaN},{...hit,lon:181},{...hit,lat:'51'},...Array(10).fill(hit)]});assert.equal(rows.length,5);assert.deepEqual(Object.keys(rows[0]).sort(),['confidence','formatted','latitude','longitude','precision']);});
 console.log(JSON.stringify({passed,productionWrites:0}));
}
main().catch(e=>{console.error(e.stack);process.exit(1);});
