// Browser -> isolated Postgres. No real accounts, locations or provider calls.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright'),{fixture}=require('./team-db-fixture.cjs');
const root=path.resolve(__dirname,'../..'),source=fs.readFileSync(path.join(root,'app-v800.js'),'utf8').replace(/\}\)\(\);\s*$/,'window.__geoTest={state,render,reload,deviceFeatures};})();');
async function main(){
 const {db,ids,actor,admin}=await fixture({offers:true,units:true,catalog:true});let passed=0,current='business',queue=Promise.resolve(),fetches=0;
 const sql=name=>fs.readFileSync(path.join(root,'supabase/migrations',name),'utf8');
 await db.exec('create role service_role bypassrls;');
 for(const name of ['20261008211721_device_features_v863.sql','20261009100224_appointment_reminders_v865.sql','20261009101042_arrival_timers_v865.sql','20261010190525_planning_sync_v867.sql','20261010214321_customer_address_geocoding_v869.sql'])await db.exec(sql(name));
 await db.query('update customers set custom_fields=$2 where id=$1',[ids.customer,JSON.stringify({street:'Teststraße',house_no:'1',city:'Testort',postal_code:'12345'})]);
 const handlerSource=fs.readFileSync(path.join(root,'supabase/functions/customer-geocoding/handler.js'),'utf8');
 const {makeGeocodingHandler}=await import('data:text/javascript;base64,'+Buffer.from(handlerSource).toString('base64'));
 const handler=makeGeocodingHandler({key:()=> 'synthetic-secret',authenticate:async()=>ids[current],rpc:async(name,args)=>{await db.exec('reset role;set role service_role');const values=Object.values(args);return (await db.query('select '+name+'('+values.map((_,i)=>'$'+(i+1)).join(',')+') result',values.map(v=>v&&typeof v==='object'?JSON.stringify(v):v))).rows[0].result;},fetchProvider:async()=>{fetches++;return Response.json({results:[{lat:51.5,lon:7,country_code:'de',formatted:'Teststraße 1, 12345 Testort',result_type:'building',rank:{confidence:1}},{lat:51.51,lon:7.01,country_code:'de',formatted:'Teststraße, anderer Abschnitt',result_type:'street',rank:{confidence:.6}}]});}});
 const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';if(name==='config.js'){res.setHeader('Content-Type','application/javascript');return res.end('window.WORKTIME_CONFIG={supabaseUrl:"https://test.invalid",supabasePublishableKey:"synthetic"}');}if(name==='app-v800.js'){res.setHeader('Content-Type','application/javascript');return res.end(source);}if(name==='service-worker.js'){res.statusCode=404;return res.end();}const file=path.resolve(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(file));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:process.platform==='win32'?'msedge':undefined,headless:true});
 try{
  const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let confirmReplace=false;page.on('dialog',d=>confirmReplace?d.accept():d.dismiss());
  await page.route('https://test.invalid/**',route=>{queue=queue.then(async()=>{const req=route.request(),u=new URL(req.url()),body=req.postData()?req.postDataJSON():null;const send=(data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});try{await actor(current);
   if(u.pathname==='/functions/v1/customer-geocoding'){const result=await handler(new Request(req.url(),{method:'POST',headers:{Authorization:'Bearer synthetic'},body:JSON.stringify(body)}));return send(await result.json(),result.status);}
   if(u.pathname.includes('/functions/'))return send({});
   if(u.pathname.includes('/rpc/')){const name=u.pathname.split('/').at(-1);if(name==='current_business_branding')return send([{id:ids.business,company_name:'Testfirma'}]);if(name==='work_order_team_context')return send((await db.query('select work_order_team_context($1) result',[body.p_company])).rows[0].result);if(name==='accept_customer_geocoding_v869')return send((await db.query('select accept_customer_geocoding_v869($1,$2,$3,$4) result',[body.p_customer,body.p_address_key,body.p_index,body.p_replace_manual])).rows[0].result);if(name==='planning_sync_stamp')return send((await db.query('select planning_sync_stamp() result')).rows[0].result);return send(null);}
   const table=u.pathname.split('/').at(-1);if(!/^[a-z_]+$/.test(table)||(await db.query("select to_regclass('public.'||$1) t",[table])).rows[0].t==null)return send([]);
   const parameters=[],where=[];for(const [key,value]of u.searchParams)if(/^[a-z_]+$/.test(key)&&value.startsWith('eq.')){parameters.push(value.slice(3));where.push(key+'=$'+parameters.length);}
   return send((await db.query('select * from '+table+(where.length?' where '+where.join(' and '):''),parameters)).rows);
  }catch(e){return send({message:e.message,code:e.code},400);}});return queue;});
  await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>!!window.__geoTest);
  const role=async name=>{await queue;await admin();current=name;const profile=(await db.query('select * from profiles where id=$1',[ids[name]])).rows[0];await page.evaluate(async({profile,ids})=>{const a=window.__geoTest;Object.assign(a.state,{profile,session:{user:{id:profile.id},access_token:'synthetic'},businessId:ids.business,employeeId:ids.anna,view:'customers',date:'2026-10-10',month:'2026-10',customerId:ids.customer});await a.reload();a.render();},{profile,ids});};
  const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
  await role('business');
  await test('Managers see address recognition; provider is never contacted just by opening customer',async()=>{assert.equal(await page.locator('[data-device-action="customer-geocode"]').count(),1);assert.equal(fetches,0);});
  await test('Unsaved address changes are preserved and block address lookup',async()=>{await page.locator('form[data-form="customer"] [name="street"]').fill('Noch nicht gespeichert');await page.locator('[data-device-action="customer-geocode"]').click();await page.waitForFunction(()=>document.querySelector('.geocoding-status').textContent.includes('zuerst speichern'));assert.equal(fetches,0);assert.equal(await page.locator('[name="street"]').inputValue(),'Noch nicht gespeichert');await page.locator('[name="street"]').fill('Teststraße');});
  await test('Find address offers building and approximate match without yet setting site',async()=>{await page.locator('[data-device-action="customer-geocode"]').click();await page.waitForFunction(()=>document.querySelectorAll('.geocoding-hit').length===2);assert.equal(fetches,1);assert.match(await page.locator('.geocoding-hit').nth(1).innerText(),/Ungefährer/);await admin();assert.equal((await db.query('select * from customer_locations')).rows.length,0);});
  await test('One chosen result stores location and fills coordinates immediately without losing customer edits',async()=>{await page.locator('[name="email"]').fill('not-saved@example.invalid');await page.locator('.geocoding-hit').first().click();await page.waitForFunction(()=>document.querySelector('.geocoding-status').textContent.includes('Kundenstandort gespeichert'));assert.equal(await page.locator('[name="latitude"]').inputValue(),'51.5');assert.equal(await page.locator('[name="email"]').inputValue(),'not-saved@example.invalid');await admin();assert.equal((await db.query('select source from customer_locations')).rows[0].source,'geoapify');});
  await test('Cached lookup does not consume provider again; attribution remains visible',async()=>{await page.locator('[data-device-action="customer-geocode"]').click();await page.waitForFunction(()=>document.querySelectorAll('.geocoding-hit').length===2);assert.equal(fetches,1);assert.match(await page.locator('[data-geocoding]').innerText(),/Geoapify.*OpenStreetMap/s);});
  await test('Manual-site replacement requires confirmation and cancellation changes nothing',async()=>{await admin();await db.query("update customer_locations set source='manual',latitude=52 where customer_id=$1",[ids.customer]);await role('business');await page.locator('[data-device-action="customer-geocode"]').click();await page.waitForFunction(()=>document.querySelectorAll('.geocoding-hit').length===2);await page.locator('.geocoding-hit').first().click();await page.waitForFunction(()=>document.querySelector('.geocoding-status').textContent.includes('bleibt unverändert'));await admin();assert.equal((await db.query('select latitude from customer_locations')).rows[0].latitude,52);});
  await test('Employee has company site for timer but cannot access the geocoding editor',async()=>{await role('anna');assert.equal(await page.locator('[data-device-action="customer-geocode"]').count(),0);await actor('anna');assert.equal((await db.query('select * from customer_locations')).rows.length,1);});
  await test('Admin view has same editor; narrow portrait, landscape and PC stay inside viewport',async()=>{await role('admin');assert.equal(await page.locator('[data-device-action="customer-geocode"]').count(),1);for(const viewport of [{width:320,height:720},{width:390,height:844},{width:844,height:390},{width:1440,height:900}]){await page.setViewportSize(viewport);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}});
  assert.deepEqual(errors,[]);console.log(JSON.stringify({passed,productionWrites:0,runtimeErrors:0}));await context.close();
 }finally{await browser.close();await new Promise(r=>server.close(r));await db.close();}
}
main().catch(e=>{console.error(e.stack);process.exit(1);});
