/* Unit snapshots and real PostgreSQL authorization/atomicity. No live writes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('./team-db-fixture.cjs');
async function main(){
  const data=await fixture({legacyRecords:true,offers:true}),{db,ids,actor,admin}=data;let passed=0,order,offer;
  const migration=fs.readFileSync(path.resolve(__dirname,'../../supabase/migrations/20261006122754_material_units_v860.sql'),'utf8')+'\n'+fs.readFileSync(path.resolve(__dirname,'../../supabase/migrations/20261006133602_material_unit_kg_v861.sql'),'utf8');
  const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
  const snapshot=async()=>{await admin();return (await db.query(`select jsonb_build_object('materials',(select jsonb_agg(to_jsonb(m)-'unit' order by id) from materials m),'items',(select jsonb_agg(to_jsonb(i)-'unit' order by id) from work_order_items i),'orders',(select jsonb_agg(w order by id) from work_orders w),'times',(select jsonb_agg(t order by id) from time_entries t),'profiles',(select jsonb_agg(p order by id) from profiles p),'offers',(select jsonb_agg(o order by id) from offers o)) value`)).rows[0].value;};
  const quote={business_id:ids.business,customer_id:ids.customer,customer_name:'Klostermanns Hof',offer_date:'2026-10-05',title:'Einheitenprüfung',status:'draft',vat_rate:19,items:[]};
  const saveQuote=async(value,revision=null)=>(await db.query('select to_jsonb(save_offer_v857($1,$2)) value',[JSON.stringify(value),revision])).rows[0].value;
  const before=await snapshot();
  try{
    await test('Migration leaves all existing business rows, amounts and times unchanged',async()=>{await db.exec(migration);assert.deepEqual(await snapshot(),before);assert.equal((await db.query('select count(*)::int n from materials where unit is not null')).rows[0].n,0);});
    await test('Migration can be applied twice without altering business data',async()=>{await db.exec(migration);assert.deepEqual(await snapshot(),before);});
    await test('Five units and legacy aliases are canonicalized without converting quantities',async()=>{for(const [input,result] of [['stk.','Stk'],[' M ','M'],['h','H'],['pau','Pau'],[' KG ','Kg'],[null,'Stk']])assert.equal((await db.query('select app_private.canonical_unit_v860($1) unit',[input])).rows[0].unit,result);assert.equal((await db.query('select app_private.canonical_unit_v860(null,true) unit')).rows[0].unit,'H');});
    await test('Catalog inserts default to pieces or hours; invalid units are rejected',async()=>{const rows=(await db.query("insert into materials(business_id,name) values($1,'Neuer Artikel'),($1,' monteurstunde ') returning unit",[ids.business])).rows;assert.deepEqual(rows.map(r=>r.unit),['Stk','H']);await assert.rejects(()=>db.query("update materials set unit='Liter' where id=$1",[ids.material]));});
    await test('Team work order stores a unit per position and bills all employee hours once',async()=>{await actor('business');order=await data.save(data.order,data.periods,['Stk','M','H','Pau','Kg'].map(unit=>({material_id:ids.material,quantity:3,unit})));const items=(await db.query('select * from work_order_items where work_order_id=$1',[order.id])).rows;assert.deepEqual(items.filter(i=>i.material_id===ids.material).map(i=>i.unit).sort(),['H','Kg','M','Pau','Stk']);assert.ok(items.filter(i=>i.material_id!==ids.material).every(i=>i.unit==='H'));assert.ok(items.filter(i=>i.material_id===ids.material).every(i=>Number(i.quantity)===3&&Number(i.unit_price)===2));assert.equal(order.team_periods.length,3);});
    await test('Explicit order unit survives catalog changes and editing',async()=>{await admin();await db.query("update materials set unit='M' where id=$1",[ids.material]);await actor('business');order=await data.save({...data.order,id:order.id},data.periods,[{material_id:ids.material,quantity:3,unit:'Pau'}]);assert.equal((await db.query('select unit from work_order_items where work_order_id=$1 and material_id=$2',[order.id,ids.material])).rows[0].unit,'Pau');});
    await test('Older clients inherit the catalog unit when they omit a unit',async()=>{await actor('business');order=await data.save({...data.order,id:order.id},data.periods,[{material_id:ids.material,quantity:3}]);assert.equal((await db.query('select unit from work_order_items where work_order_id=$1 and material_id=$2',[order.id,ids.material])).rows[0].unit,'M');});
    await test('Invalid order units roll back the entire order, item and time transaction',async()=>{const previous=await snapshot();await actor('business');await assert.rejects(()=>data.save({...data.order,id:order.id,title:'Must roll back'},data.periods,[{material_id:ids.material,quantity:3,unit:'Liter'}]));assert.deepEqual(await snapshot(),previous);});
    await test('Quotation stores all five units with unchanged decimal prices and totals',async()=>{await actor('business');offer=await saveQuote({...quote,items:['Stk','M','H','Pau','Kg'].map(unit=>({kind:'material',material_id:ids.material,name:'Kabel',quantity:3,unit_price:2,unit}))});assert.deepEqual(offer.items.map(i=>i.unit),['Stk','M','H','Pau','Kg']);assert.equal(offer.subtotal,30);assert.equal(offer.total,35.7);});
    await test('Quotation unit overrides survive reload, catalog updates and revision edits',async()=>{await admin();await db.query("update materials set unit='H' where id=$1",[ids.material]);await actor('business');offer=await saveQuote({...offer,title:'Bearbeitet'},offer.revision);assert.deepEqual(offer.items.map(i=>i.unit),['Stk','M','H','Pau','Kg']);});
    await test('Invalid quotation units cannot partially save or increment its revision',async()=>{await actor('business');await assert.rejects(()=>saveQuote({...offer,items:[{...offer.items[0],unit:'Liter'}]},offer.revision));const row=(await db.query('select revision,items from offers where id=$1',[offer.id])).rows[0];assert.equal(row.revision,offer.revision);assert.deepEqual(row.items,offer.items);});
    await test('Unit helpers do not add anonymous RPC privileges or weaken company isolation',async()=>{await actor('otherBusiness');assert.equal((await db.query('select * from work_order_items')).rows.length,0);assert.equal((await db.query('select * from offers')).rows.length,0);await assert.rejects(()=>data.save({...data.order,id:order.id},data.periods,[{material_id:ids.material,quantity:3,unit:'M'}]));await admin();assert.equal((await db.query("select has_function_privilege('anon','app_private.canonical_unit_v860(text,boolean)','execute') allowed")).rows[0].allowed,false);assert.equal((await db.query("select count(*)::int n from pg_class where oid in ('materials'::regclass,'work_order_items'::regclass) and relrowsecurity")).rows[0].n,2);});
    console.log(JSON.stringify({passed,productionWrites:0}));
  }finally{await db.close();}
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
