/* Quotations tested against disposable PostgreSQL with actual RLS. */
const assert=require('node:assert/strict');
const {fixture}=require('./team-db-fixture.cjs');
async function main(){
  const {db,ids,actor,admin}=await fixture({legacyRecords:true,offers:true});let passed=0;
  const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
  const save=async(data,revision=null)=>(await db.query('select to_jsonb(save_offer_v857($1::jsonb,$2)) result',[JSON.stringify(data),revision])).rows[0].result;
  const remove=async(row,revision=row.revision)=>db.query('select delete_offer_v857($1,$2)',[row.id,revision]);
  const reject=async(fn)=>assert.rejects(fn);
  const base={business_id:ids.business,customer_id:ids.customer,customer_name:'Klostermanns Hof',customer_snapshot:{street:'Teststraße',house_no:'12',city:'Dortmund',postal_code:'44135'},offer_date:'2026-10-05',valid_until:'2026-11-05',title:'Montage & Material',notes:'Notiz mit Leerzeichen',status:'draft',vat_rate:19,items:[{kind:'labor',material_id:ids.monteur,name:'Monteurstunde',quantity:2.25,unit_price:55},{kind:'material',material_id:ids.material,name:'Kabel',quantity:3,unit_price:2}]};
  const unchanged=async()=>{await admin();return (await db.query("select jsonb_build_object('profiles',(select jsonb_agg(p order by id) from profiles p),'days',(select jsonb_agg(d order by employee_id,work_date) from work_days d),'vacations',(select jsonb_agg(v order by id) from vacation_requests v),'appointments',(select jsonb_agg(a order by id) from appointments a),'entries',(select jsonb_agg(t order by id) from time_entries t),'orders',(select jsonb_agg(w order by id) from work_orders w)) data")).rows[0].data;};
  const before=await unchanged();let first,second;
  try{
    await test('Business creates a quote with canonical labor/material prices and exact totals',async()=>{await actor('business');first=await save({...base,subtotal:0,total:0,created_by:ids.felix});assert.equal(first.subtotal,129.75);assert.equal(first.tax_amount,24.65);assert.equal(first.total,154.4);assert.equal(first.items[0].line_total,123.75);assert.equal(first.created_by,ids.business);assert.equal(first.revision,1);assert.match(first.offer_number,/^ANG-2026-[0-9A-F]{12}$/);});
    await test('Employee cannot read, save, delete, or directly insert quotations',async()=>{await actor('anna');assert.equal((await db.query('select * from offers')).rows.length,0);await reject(()=>save(base));await reject(()=>remove(first));await reject(()=>db.query("insert into offers(business_id,created_by,offer_number,customer_name,title,items) values($1,$2,'FAKE','Test','Test',$3)",[ids.business,ids.anna,JSON.stringify(base.items)]));});
    await test('Employee direct SQL changes cannot alter an existing quotation',async()=>{await actor('anna');assert.equal((await db.query('update offers set title=\'forbidden\' returning id')).rows.length,0);assert.equal((await db.query('delete from offers returning id')).rows.length,0);});
    await test('Another company cannot read or change a quotation',async()=>{await actor('otherBusiness');assert.equal((await db.query('select * from offers')).rows.length,0);await reject(()=>save({...base,id:first.id},first.revision));await reject(()=>remove(first));});
    await test('Administrator may manage a different company',async()=>{await actor('admin');second=await save({...base,business_id:ids.otherBusiness,customer_id:ids.otherCustomer,customer_name:'Anderer Kunde',items:[{kind:'material',name:'Freie Position',quantity:1,unit_price:0}]});assert.equal(second.total,0);assert.equal(second.created_by,ids.admin);});
    await test('Companies retain independent quotations, including the same customer display name',async()=>{await actor('otherBusiness');const rows=(await db.query('select * from offers')).rows;assert.equal(rows.length,1);assert.equal(rows[0].id,second.id);await actor('admin');assert.equal((await db.query('select * from offers')).rows.length,2);});
    await test('Anonymous access and quotation RPC execution are denied',async()=>{await admin();await db.exec('set role anon');await reject(()=>db.query('select * from offers'));await reject(()=>save(base));await reject(()=>remove(first));});
    await test('Foreign customer and material identifiers cannot be smuggled into a quote',async()=>{await actor('business');await reject(()=>save({...base,customer_id:ids.otherCustomer}));await actor('otherBusiness');await reject(()=>save({...base,business_id:ids.otherBusiness,customer_id:ids.otherCustomer,items:[base.items[0]]}));});
    await test('Invalid labor steps, negative prices, empty/oversized items and date ranges are rejected',async()=>{await actor('business');for(const items of [[],Array(101).fill(base.items[0]),[{...base.items[0],quantity:0.3}],[{...base.items[0],unit_price:-1}],[{...base.items[0],quantity:0}],[{...base.items[0],unit_price:1000001}],[{...base.items[0],kind:'invalid'}]])await reject(()=>save({...base,items}));await reject(()=>save({...base,valid_until:'2026-10-01'}));});
    await test('Half-cent rounding matches PostgreSQL decimal arithmetic',async()=>{await actor('business');const row=await save({...base,items:[{kind:'material',name:'Test',quantity:0.5,unit_price:0.29}],vat_rate:0});assert.equal(row.subtotal,0.15);await remove(row);});
    await test('Saved prices and customer snapshots do not change when catalog prices change',async()=>{await admin();await db.query('update materials set unit_price=99 where id=$1',[ids.monteur]);await db.query('update customers set custom_fields=\'{"city":"Berlin"}\' where id=$1',[ids.customer]);await actor('business');const row=(await db.query('select to_jsonb(o) value from offers o where id=$1',[first.id])).rows[0].value;assert.equal(row.items[0].unit_price,55);assert.equal(row.customer_snapshot.city,'Dortmund');});
    await test('Editing uses a revision, preserves identifiers and prevents lost updates',async()=>{await actor('business');first=await save({...first,title:'Bearbeitet',items:[{...first.items[0],quantity:3.25},first.items[1]]},first.revision);assert.equal(first.revision,2);assert.equal(first.subtotal,184.75);await reject(()=>save({...first,title:'Alter Stand'},1));await reject(()=>remove(first,1));});
    await test('Direct table writes cannot falsify computed totals or migrate a quote between companies',async()=>{await actor('business');const row=(await db.query('update offers set total=0,subtotal=0,revision=999,offer_number=\'FAKE\' where id=$1 returning to_jsonb(offers) value',[first.id])).rows[0].value;assert.equal(row.total,219.85);assert.equal(row.revision,3);assert.equal(row.offer_number,first.offer_number);first=row;await actor('admin');await reject(()=>db.query('update offers set business_id=$1 where id=$2',[ids.otherBusiness,first.id]));});
    await test('Deleted catalog/customer records keep the saved offer usable as an independent snapshot',async()=>{await admin();const cid=(await db.query("insert into customers(employee_id,name) values($1,'Löschbarer Kunde') returning id",[ids.anna])).rows[0].id,mid=(await db.query("insert into materials(business_id,name,unit_price) values($1,'Löschbarer Artikel',7) returning id",[ids.business])).rows[0].id;await actor('business');let row=await save({...base,customer_id:cid,customer_name:'Löschbarer Kunde',items:[{kind:'material',name:'Löschbarer Artikel',material_id:mid,quantity:1,unit_price:7}]});await admin();await db.query('delete from materials where id=$1',[mid]);await db.query('delete from customers where id=$1',[cid]);await actor('business');row=await save({...row,title:'Noch bearbeitbar'},row.revision);assert.equal(row.customer_id,null);assert.equal(row.items[0].material_id,null);assert.equal(row.items[0].unit_price,7);await remove(row);});
    await test('Delete is immediate and does not resurrect on reload',async()=>{await actor('business');await remove(first);assert.equal((await db.query('select * from offers')).rows.length,0);await actor('admin');await remove(second);assert.equal((await db.query('select * from offers')).rows.length,0);});
    await test('Offers never change profiles, plans, bookings, leave, sickness or existing work orders',async()=>assert.deepEqual(await unchanged(),before));
    console.log(JSON.stringify({passed,productionWrites:0}));
  }finally{await db.close();}
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
