/* Synthetic auth responses only. No credentials or production requests. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const app=fs.readFileSync(path.resolve(__dirname,'../../app-v800.js'),'utf8');
const source=app.slice(app.indexOf('  function createSessionAuth('),app.indexOf('  /* END SESSION AUTH V859 */'))+'\nwindow.WorktimeAuth={create:createSessionAuth};';
const clock=1_800_000_000,storageName='test-session';
const token=(exp,label='old')=>'header.'+Buffer.from(JSON.stringify({exp})).toString('base64url')+'.'+label;
const session=(label='old',exp=clock-1,user='business')=>({access_token:token(exp,label),refresh_token:'synthetic-'+label,expires_at:exp,user:{id:user}});
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
function locks(){const chains=new Map();return {request(name,fn){const pending=(chains.get(name)||Promise.resolve()).catch(()=>{}).then(fn);chains.set(name,pending);return pending;}};}
function environment(handler,initial=session(),shared={map:new Map(),locks:locks()}){
  let current=initial;
  const localStorage={getItem:key=>shared.map.get(key)||null,setItem:(key,value)=>shared.map.set(key,String(value)),removeItem:key=>shared.map.delete(key)};
  if(initial&&!localStorage.getItem(storageName))localStorage.setItem(storageName,JSON.stringify(initial));
  const scope={window:{},navigator:{locks:shared.locks},localStorage,Headers,atob,Date:{now:()=>clock*1000},fetch:handler};vm.runInNewContext(source,scope);
  const auth=scope.window.WorktimeAuth.create({base:'https://test.invalid',key:'public-test',storage:storageName,getSession:()=>current,setSession:value=>{current=value;}});
  return {auth,localStorage,get:()=>current,set:value=>{current=value;},shared};
}
async function main(){let passed=0;const test=async(name,fn)=>{await fn();passed++;console.log('PASS '+name);};
  await test('Expired sessions rotate both tokens and persist the new expiry before a write',async()=>{
    const calls=[],fresh=session('new',clock+3600);const e=environment(async(url,options)=>{calls.push({url,options});return url.includes('refresh_token')?json(fresh):json({saved:true});});
    await e.auth.request('/rest/v1/rpc/save_offer_v857',{method:'POST',body:'{}'});
    assert.equal(calls.length,2);assert.equal(calls[0].options.headers.Authorization,undefined);assert.equal(JSON.parse(calls[0].options.body).refresh_token,'synthetic-old');assert.equal(calls[1].options.headers.get('Authorization'),'Bearer '+fresh.access_token);assert.equal(JSON.parse(e.localStorage.getItem(storageName)).refresh_token,fresh.refresh_token);
  });
  await test('JWT exp is used for restored sessions without expires_at',async()=>{let count=0;const old=session();delete old.expires_at;const e=environment(async url=>{if(url.includes('refresh_token'))count++;return json(session('new',clock+3600));},old);await e.auth.ensure();assert.equal(count,1);});
  await test('Twenty simultaneous requests share exactly one refresh',async()=>{let count=0,requests=0;const e=environment(async url=>{if(url.includes('refresh_token')){count++;await new Promise(resolve=>setTimeout(resolve,20));return json(session('new',clock+3600));}requests++;return json([]);});await Promise.all(Array.from({length:20},()=>e.auth.request('/rest/v1/offers')));assert.equal(count,1);assert.equal(requests,20);});
  await test('A server JWT expiry rejection is retried once, with exactly one committed write',async()=>{let count=0,attempts=0,writes=0;const e=environment(async(url,options)=>{if(url.includes('refresh_token')){count++;return json(session('new',clock+3600));}attempts++;if(options.headers.get('Authorization').endsWith('.old'))return json({code:'PGRST301',message:'JWT expired'},401);writes++;return json({saved:true});},session('old',clock+3600));await e.auth.request('/rest/v1/rpc/save_offer_v857',{method:'POST',body:'{}'});assert.equal(count,1);assert.equal(attempts,2);assert.equal(writes,1);});
  await test('A second JWT expiry response does not enter a retry loop',async()=>{let attempts=0,refreshes=0;const e=environment(async url=>{if(url.includes('refresh_token')){refreshes++;return json(session('new',clock+3600));}attempts++;return json({message:'JWT expired'},401);},session('old',clock+3600));await assert.rejects(()=>e.auth.request('/rest/v1/offers'),error=>error.code==='SESSION_EXPIRED');assert.equal(attempts,2);assert.equal(refreshes,1);});
  await test('RLS denials and unrelated unauthorized errors never refresh or retry',async()=>{for(const code of [401,403]){let calls=0;const e=environment(async()=>{calls++;return json({message:'Permission denied'},code);},session('old',clock+3600));assert.equal((await e.auth.request('/rest/v1/offers')).status,code);assert.equal(calls,1);}});
  await test('Server and network failures never replay a possibly committed write',async()=>{for(const network of [false,true]){let calls=0;const e=environment(async()=>{calls++;if(network)throw Error('offline');return json({message:'service unavailable'},503);},session('old',clock+3600));if(network)await assert.rejects(()=>e.auth.request('/rest/v1/rpc/save_offer_v857',{method:'POST'}));else assert.equal((await e.auth.request('/rest/v1/rpc/save_offer_v857',{method:'POST'})).status,503);assert.equal(calls,1);}});
  await test('Invalid refresh tokens prevent the save and return a clear sign-in message',async()=>{let calls=0;const e=environment(async()=>{calls++;return json({code:'refresh_token_not_found'},400);});await assert.rejects(()=>e.auth.request('/rest/v1/offers'),error=>error.code==='SESSION_EXPIRED'&&/erneut anmelden/.test(error.message));assert.equal(calls,1);assert.equal(e.get().refresh_token,'synthetic-old');});
  await test('Temporary refresh outages retain the previous session for a later attempt',async()=>{let calls=0;const e=environment(async()=>{calls++;throw Error('offline');});await assert.rejects(()=>e.auth.ensure(),error=>error.code==='SESSION_REFRESH_UNAVAILABLE');assert.equal(calls,1);assert.equal(e.get().refresh_token,'synthetic-old');});
  await test('Late refresh responses cannot resurrect a logged-out account',async()=>{let finish,started;const begin=new Promise(resolve=>{started=resolve;});const e=environment(async()=>{started();return new Promise(resolve=>{finish=resolve;});});const pending=e.auth.ensure();await begin;e.auth.clear();finish(json(session('new',clock+3600)));await assert.rejects(()=>pending,error=>error.code==='SESSION_CHANGED');assert.equal(e.get(),null);assert.equal(e.localStorage.getItem(storageName),null);});
  await test('Late refresh responses cannot overwrite a newer login, even for the same user',async()=>{let finish,started;const begin=new Promise(resolve=>{started=resolve;});const e=environment(async()=>{started();return new Promise(resolve=>{finish=resolve;});});const pending=e.auth.ensure();await begin;e.auth.install(session('new-login',clock+3600));finish(json(session('refresh',clock+3600)));await assert.rejects(()=>pending,error=>error.code==='SESSION_CHANGED');assert.equal(e.get().refresh_token,'synthetic-new-login');});
  await test('Two tabs serialize token rotation and the second adopts the fresh token',async()=>{let calls=0;const shared={map:new Map(),locks:locks()},handler=async()=>{calls++;await new Promise(resolve=>setTimeout(resolve,15));return json(session('new',clock+3600));},a=environment(handler,session(),shared),b=environment(handler,session(),shared);await Promise.all([a.auth.ensure(),b.auth.ensure()]);assert.equal(calls,1);assert.equal(a.get().access_token,b.get().access_token);});
  await test('A second tab cannot renew a session removed by logout in the first tab',async()=>{let calls=0;const shared={map:new Map(),locks:locks()},handler=async()=>{calls++;return json(session('new',clock+3600));},a=environment(handler,session(),shared),b=environment(handler,session(),shared);a.auth.clear();await assert.rejects(()=>b.auth.ensure(),error=>error.code==='SESSION_CHANGED');assert.equal(calls,0);assert.equal(b.localStorage.getItem(storageName),null);});
  await test('Password sign-in bypasses expired previous credentials and does not send their bearer token',async()=>{let calls=0;const e=environment(async(url,options)=>{calls++;assert.ok(url.endsWith('grant_type=password'));assert.equal(options.headers.get('Authorization'),null);return json(session('login',clock+3600));});await e.auth.request('/auth/v1/token?grant_type=password',{method:'POST',body:'{}'});assert.equal(calls,1);});
  await test('Fresh sessions and anonymous requests do not require refresh tokens',async()=>{const seen=[];const old={access_token:'synthetic',user:{id:'business'}};const e=environment(async(url,options)=>{seen.push(options.headers.get('Authorization'));return json([]);},old);await e.auth.request('/rest/v1/offers');e.auth.clear();await e.auth.request('/functions/v1/password-reset');assert.deepEqual(seen,['Bearer synthetic',null]);});
  await test('Storage uploads keep their binary body and headers through a JWT-only retry',async()=>{const file=new Blob(['synthetic attachment'],{type:'text/plain'});let attempts=0;const e=environment(async(url,options)=>{if(url.includes('refresh_token'))return json(session('new',clock+3600));attempts++;assert.equal(options.body,file);assert.equal(options.headers.get('x-upsert'),'false');return attempts===1?json({message:'JWT has expired'},401):json({id:'file'});},session('old',clock+3600));await e.auth.request('/storage/v1/object/files/test.txt',{method:'POST',headers:{'x-upsert':'false','Content-Type':file.type},body:file});assert.equal(attempts,2);});
  await test('Unexpected refresh identities and another tab account never replace the current user',async()=>{const e=environment(async()=>json(session('wrong',clock+3600,'another-account')));await assert.rejects(()=>e.auth.ensure(),error=>error.code==='SESSION_EXPIRED');assert.equal(e.get().user.id,'business');const a=environment(async()=>{throw Error('must not call');});a.localStorage.setItem(storageName,JSON.stringify(session('another',clock+3600,'another-account')));await assert.rejects(()=>a.auth.ensure(),error=>error.code==='SESSION_CHANGED');assert.equal(a.get().user.id,'business');});
  await test('Session installation normalizes expires_in without renewing a restored stale expiry',async()=>{const e=environment(async()=>json({}));const data={access_token:'synthetic',refresh_token:'synthetic-new',user:{id:'business'},expires_in:3600};e.auth.install(data);assert.equal(e.get().expires_at,clock+3600);});
  console.log(JSON.stringify({passed,productionRequests:0}));
}
main().catch(error=>{console.error(error.stack);process.exitCode=1;});
